### ISSUE TITLE
Pre/Post commands with parameters

### ISSUE THREAD

**Issue by dimmuboy** [FreeRDP/Remmina#1010]
Hello,
how can I put pre or post commands to RDP connection with some parameters?
If I try to connect VPN through nmcli I got warning

> WARNING **: Failed to execute child process "nmcli con up id 'vpn'" (No such file or directory)

Is there way to run command with parameters with special syntax or I must make direct script for each VPN which I need?

**Comment by antenore** [comment]
Yes, unlucky, at the moment the parameters are not supported (sorry, my bad). I'll work on it some day, but, in the meanwhile, there is a really simple workaround.

It's just enough that you write a script with inside all the commands/parameters you need and then point in the pre/post commands the **full path** fo the script.

I've highlighted **full path** because otherwise the script won't be found.

**Comment by antenore** [comment]
I close this because somewhere we have a duplicated of this.

Let me know anyway if the workaround works.
