### ISSUE TITLE
Security Issue?

### ISSUE THREAD

**Issue by gusennan** [FreeRDP/Remmina#1027]
I'm not sure how this happened, but here's the situation:

I logged into a user on an OSX system through Renmina
I logged into that same user on the actual OSX system, meaning the desktops were mirrored
When a user logged into another user account from that OSX account on the computer, the renmina followed that user across accounts and I ended up with desktop access to an account that I never signed into on my remote computer.

Please give us some details about the systems you are using:
* Fedora 24
* 1.2.0-0.13.rcgit.7.fc24
* Gnome
* OSX
* VNC

**Comment by antenore** [comment]
Thanks so much for reporting security issues.

It is indeed, but not because of Remmina. 
I would say that is an OS and protocol issue, so maybe I would submit a security bug report to Apple, but I'm afraid they will misunderstood the issue.

Try it out if you want and let me know if I can help (privately, check my email in the remmina about dialog).

Closing this as out of scope.
