### ISSUE TITLE
Importing rdp file not successful

### ISSUE THREAD

**Issue by joostkremers** [FreeRDP/Remmina#1039]
I was sent an `.rdp` file to connect to a remote Windows desktop, but importing it into Remmina was not completely successful. Most importantly, it hadn't picked up the `gatewayhostname` option, which meant I was not able to connect to the server.

I'm afraid I cannot provide the `.rdp` file in question, so this may not be a very helpful report, but I thought I'd inform you anyway. If there is anything you wish to ask or anything you want me to try out, just let me know and I'll see if I can help.

I'm not sure if the details about OS etc. are really relevant, but just to be complete:

* Client (OS name and version): Linux (Elementary OS 0.4, based on Ubuntu 16.04)
* Remmina version (remmina --version): 1.2.0-rcgit-15 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): 
* Connecting to (OS and version): Windows Server 2012 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0~dev (git n/a)

**Comment by antenore** [comment]
Can you please provide the rdp file without the values? We just need the parameter names.

Over here https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/rdp/rdp_file.c#L61 is where we import the rdp parameter/values and I think that @giox069 didn't have an RDP Gateway available to do some tests (we don't have it yet)... That's why we need an RDP file, even with false or empty values.

**Comment by joostkremers** [comment]
Hi, just FYI: I haven't been able to post the rdp parameter names, unfortunately, but I received an updated rdp file today and was able to import it without issues. The gateway was recognised correctly and so were all other parameter values.
