### ISSUE TITLE
Advanced Settings for RDP connections

### ISSUE THREAD

**Issue by jwhipp** [FreeRDP/Remmina#1043]
Please give us some details about the systems you are using:
* Client (OS name and version):  Ubuntu 14.04, 16.04, 16.10
* Remmina version (remmina --version):   remmina - Version 1.2.0-rcgit-15 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..):  Unity
* Connecting to (OS and version):  Windows 10
* Connecting via (RDP, VNC, ...):  RDP
* RDP issues only, freerdp version (xfreerdp --version):  This is FreeRDP version 2.0.0~dev (git n/a)

This is a feature request.  I'd really like to see a way with in the Remmina gui to configure advanced options of xfreerdp such as things like rdp8/gfx, rfx, compression, etc.  Even if this was a text box that you could pop cli arguments into, that'd be great.  I end up using xfreerdp on the cli because I can only use the rdp8 stuff through that which is inconvenient compared to the Remmina GUI.

**Comment by jwhipp** [comment]
One thing to add to that, you can do dual or full screen with the client, another HUGE addition to the gui options.

**Comment by antenore** [comment]
Remmina doesn't use the xfreerdp executable but the libraries has been written with.
Therefore is not possible to do what you ask till we won't implement each feature available in FreeRDP.

Unlucky it's a quite big job and it takes time.

The fullscreen/multihead option is in progress #376  #961 and I hope to be able to finish it in some weeks.

If you don't mind I'll close this because 

1) Cannot be implemented as you ask
2) Mult monitor is a duplicate

**Comment by jwhipp** [comment]
Do the libraries Remmina uses support some of that functionality?  Sorry I was positive on the integration levels of xfreerdp/remmina/libs.

**Comment by antenore** [comment]
Yes, sure, most of.

We could also develop a wrapper around xfreerdp, but soon a gtk functionality that would allow us to use directly the xfreerdp executable, will be deprecated.

Beside the multi head / full screen that already exists, if you need anything else just open a new feature request.

**Comment by jwhipp** [comment]
Thanks for info, I'll ponder that and open separate requests.
