### ISSUE TITLE
RDP to Windows 10 freezes/hangs

### ISSUE THREAD

**Issue by canefield** [FreeRDP/Remmina#1139]
Dear Remmina/Support/All,

Can you help me out here...I'm using Ubuntu Mate (Raspberry Pi 3; 1GB RAM), installed the powerful Remmina, but after connecting to a Windows 10 environment the screen and connection maintains, I can move the cursus around the screen, although I can't do anything. After disconnecting and connecting again I can proceed where I left off. Just for an example, I logged in and opened Mozilla Firefox. I can see it is starting but suddenly the screen 'hangs'. After reconnecting I got the full Mozilla Firefox in front of me. Again after closing and opening the same event occurs. This is also with other programs like Adobe, Start Menu, etc.

Doing the same while connecting from a Windows machine towards the same Windows 10 environment, everything works smoothly. Is it a settings within Remmina I've to change?

Current settings: Protocol: RDP, Resolution: Use client resolution, Color depth: True color (32bpp), Quality: Best.
I've played with these settings with a less color depth and quality, but that doesn't seem to resolve the screen hangs.

Second, is there a way to upgrade to the newest Remmina in Ubuntu Mate (RPi 3)?

Many thanks already,
Canefield

=== ===
Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu Mate 16.04.2, Raspberry Pi 3 (1GB RAM)
* Remmina version (remmina --version): 1.1.2
* Desktop environment (GNOME, Unity, KDE, ..): GNOME 2
* Connecting to (OS and version): Windows 10
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 1.1.0-beta1

**Comment by transistor1** [comment]
@canefield: it's been a while since I've used my old rpi, but I can try to give you a couple of pointers.

Since you're on Ubuntu, one thing to try would be using a [PPA](https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily).  On your rpi, try:

```
sudo apt-get purge remmina freerdp
sudo add-apt-repository ppa:remmina-ppa-team/freerdp-daily
sudo apt-get update
sudo apt-get install remmina
```

If you can't find a PPA for someone who's already built it, the other way to get the latest Remmina would be to cross-compile it yourself for ARM.  This isn't a [trivial](http://stackoverflow.com/a/19269715) project, especially if you're not used to cross compiling.  Since you're starting from source, the other challenge is to produce a .deb file that's installable on your rpi.  Checkinstall is a good utility to create packages on-the-fly.

It's been a while since I've done a cross-compile, but the tricky part is getting your build environment correct.  A good way to get a build environment set up is to use Docker, and try an image like [philipz/raspberry-pi-crosscompile](https://hub.docker.com/r/philipz/raspberry-pi-crosscompile/), or [sdthirwall/raspberry-pi-cross-compiler](https://hub.docker.com/r/sdthirlwall/raspberry-pi-cross-compiler/).  Using Docker is beyond the scope of this issue, though.

**Comment by giox069** [comment]
The fastest solution on Raspberry PI 2/3 to install an updated version of Remmina, is to use our **remmina-next** PPA.
Instructions are in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki), but you just need the following commands:
```
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
```

**Comment by kalandarisvili** [comment]
Dear Remmina,
Similar issue here using Remmina on Raspbian Kernel version: 4.9 (PI model 3 B). 

Obtained Remmina through apt-get install. The RDP connection to Windows 10 VMs often freezes when opening google chrome tabs. However, if you disconnect and connect again - everything is right where you left it. The behavior is also very irregular - sometimes users can work half of the day without having the issue and sometimes it happens every hour. 

Our intention is to use PI 3 B together with Remmina as a thin client for RDP connection to the Windows 10 VMs. At this moment the connection is far from stable.

**Comment by antenore** [comment]
@kalandarisvili sorry if I ask, but I'm not sure. Did you install remmina using our PPA? can you paste the remmina version (from command line remmina --version).

**Comment by antenore** [comment]
@kalandarisvili  The official version is too old and not supported anymore, have look in the wiki, we have a page that explain how to upgrade Remmina to the last version on Debian.

The Debian team is working on this.

**Comment by giox069** [comment]
On Raspbian based on Debian 8 (or 9) the only way to have a fresh remmina is to compile it by hand. If you don't want to compile remmina by hand, you can install xubuntu on raspberry pi and use our ubuntu PPA as explained on the wiki.
Unfortunately we really don't know when Remmina will be available on debian 9.

**Comment by kalandarisvili** [comment]
@antenore @giox069 Thank you for the suggestions, I will try to follow the instructions for compiling Remmina on Debian, if It fails then I'll try your Ubuntu PPA. Will report as soon as the issue goes away.

**Comment by kalandarisvili** [comment]
Installed Ubuntu Mate 16.04 on Raspberry PI 3B and installed Remmina using Ubuntu PPA as described by giox069: 
`sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard`

So far the connection to WIN10 VMs works without interruptions. Thank you for the help @antenore @giox069!

**Comment by antenore** [comment]
Cool! Let's keep this opened some more few days than.
