### ISSUE TITLE
Build 1.2.0-rcgit.x on Debian Jessie

### ISSUE THREAD

**Issue by abhijit86k** [FreeRDP/Remmina#1147]
-

**Comment by abhijit86k** [comment]
I'm trying to compile from source on Debian Jessie, which is not mentioned build section on the Wiki. Is there any reason this will not work and therefore 1.2x will not compile on Debian Jessie? I'd like to know before I begin trying to compile from source.

**Comment by transistor1** [comment]
@abhijit86k - if you simply want to build the `next` branch, try using my Docker image, [transistor1/remmina_devel](https://hub.docker.com/r/transistor1/remmina_devel/).

First, [install Docker on debian](https://docs.docker.com/engine/installation/linux/debian/), then run (note the `:jessie` appended to the container name!!):

```
sudo docker run --rm -ti -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME:/root -e DISPLAY=unix$DISPLAY transistor1/remmina_devel:jessie bash
```

You'll be dropped into a `bash` shell within the Docker container.  Then, run:

```
/build.sh
```
All the source should be downloaded automatically, and as long as both the `freerdp` and the `remmina` master branches are not broken, it should automatically compile the `master` branch of both.

When you're asked any questions, simply press `Enter` to select the defaults.  This is just `checkinstall` building some simple `.deb` packages for you.

After building, when you `exit` the Docker container, you should see a new folder, `remmina_devel`, in your user's $HOME directory, with subfolders `FreeRDP` and `Remmina`.  In them, there will be a `freerdp_YYYYMMDD-1_amd64.deb`, and a `remmina_YYYYMMDD-1_amd64.deb`, respectively.

You can then install these .debs on your host system.  Just be aware that they don't have any dependency information baked in, so you may have to install other packages in order to get them to work.  To get an idea of some of the libraries you may need, see my Dockerfile source [here](https://github.com/transistor1/remmina_devel/blob/master/Dockerfile).

**Comment by mcrapet** [comment]
Hi,

Regarding Debian compilation of remmina.
Initially I installed dependencies:
```
$ apt-get install libgcrypt20-dev libavahi-ui-gtk3-dev libssh-dev libappindicator3-dev \
      libvncserver-dev libxkbfile-dev libtelepathy-glib-dev libsecret-1-dev
```
I faced the following issue:
* `libssl1.0-dev` is wanted by `libssh-dev`
* `libssl-dev` is wanted by `freerdp2-dev` and `libwinpr2-dev`

I bypassed dependency check with the following commands:
```
$ apt-get install libssl1.0-dev libssh-dev
$ apt-get download freerdp2-dev libwinpr2-dev
$ dpkg -i --ignore-depends=libssl-dev libwinpr2-dev_2.0.0~git20161130.1.e60d0d5+dfsg1-1_amd64.deb 
$ dpkg -i --ignore-depends=libssl-dev freerdp2-dev_2.0.0~git20161130.1.e60d0d5+dfsg1-1_amd64.deb 
```

Hope this helps.

**Comment by abhijit86k** [comment]
@transistor1 I followed your steps to install and build the deb files. I'm able to install FreeRDP, but when installing Remmina the system complains that the existing plugins are not compatible.
"Breaks existing package 'remmina-plugin-rdp' dependency remmina (= 1.1.1-2)" and same for remmina-plugin-vnc.

If i "force" install with dpkg, remmina starts up but cannot connect to any servers; complaining that "Protocol plugin RDP is not installed".

Where can I get the updated plugins?

**Comment by abhijit86k** [comment]
@mcrapet I'm running Jessie: and did not encounter any issues with the dependencies you noted above.

**Comment by transistor1** [comment]
@abhijit86k - get rid of the built-in Debian plugins before you install the Docker-compiled version.  You don't need them.  The Docker-compiled package has them built in.  I think the Debian maintainers must separate them out into different packages.  See my remmina-next screenshot below.

![image](https://cloud.githubusercontent.com/assets/5625360/25349563/4284c83c-28f0-11e7-8209-fd419b5381b5.png)

**Comment by abhijit86k** [comment]
Yes that's correct. I uninstalled freerdp-X11 also, along with the remmina-plugin-* packages.
Also, remmina was running in the tray, so had to 'pkill remmina' as well. All working now. Thanks @transistor1 !

**Comment by ic3d** [comment]
Hi @abhijit86k I'm closing this issue, feel free to open it again if needed. Thanks!
