### ISSUE TITLE
Multiple NICs

### ISSUE THREAD

**Issue by martinezjr231** [FreeRDP/Remmina#1188]
Please give us some details about the systems you are using:
* Client (OS name and version): openSUSE 42.1 x64
* Remmina version (remmina --version):  0.9.99.1 (only available with openSUSE 42.1)
* Desktop environment (GNOME, Unity, KDE, ..):  Xfce
* Connecting to (OS and version): Win 7 Pro 32bit
* Connecting via (RDP, VNC, ...):  both
* RDP issues only, freerdp version (xfreerdp --version):    Due to security setting on the WAN here, only able to connect to other devices with DHCP.  Local machine has dual NICs, one Static IP(primary), one DHCP.  I use the static to connect to other linux machines within LAN. But windows machines has to connect via DHCP, as validation goes thru AD.

**Comment by giox069** [comment]
I don't think this issue is related with Remmina: every TCP/IP client usually does not allow the user to select which interface/ip to use when connecting to a server. The interface choice is usually done by the kernel by default, which selects the best interface according to the IP routing table.
And remmina can not do anything to change this, because TCP connections sockets are not handled by remmina but by the protocol library (libfreerdp in case of RDP).
I can only advise you to check better your routing table, and try to understand why the kernel chooses one interface and not the other (are the 2 interface ip address on the same IP subnet? is the destination server on the subnet1 or subnet2 or outside of both subnets? On which interface is the default gateway? The host you are connecting to, needs to be reached via the default gw?)

**Comment by giox069** [comment]
Is it solved? Can I close this issue?

**Comment by weberhofer** [comment]
@giox069 I fully agree to your statement. If possible, freerdp must offer a option to select the IP-address to bind. I think there is nothing which can be done at the remmina-side.

**Comment by martinezjr231** [comment]
There are other programs that can be told which IP on the local machine can be set, ssh, rcp, traceroute, ping, etc...., even connecting to a MySQL server can be set.  But all those have to be set in a command line format, and not via the GUI.  That is not a problem, but it would be a great idea to have that option.

**Comment by antenore** [comment]
It's possible setting the  SO_BINDTODEVICE socket option, but it's probably something that must be implemented at freerdp level first of all.
Ask to them as well.
I'd keep this opened and if there'll be enough requests to implement it we could put some effort.
But careful, this option works only with root, so the risks are higher than the gains.
I'd definitely looks in other solutions, like NAT for example

**Comment by giox069** [comment]
Maybe using "network namespaces" as explained [here](https://unix.stackexchange.com/questions/210982/bind-unix-program-to-specific-network-interface) can help ?

**Comment by antenore** [comment]
Ah! @giox069 this is really cool! I didn't know about this, I'm getting old!!!!
