### ISSUE TITLE
Remmina crashes each time I use FTP transfer

### ISSUE THREAD

**Issue by win2win** [FreeRDP/Remmina#1257]
I use the 1.2.0-rcgit-19 (git rcgit-19) and run Ubuntu 16.04 LTS.
After updating from previous version, the software consistently crashes after using FTP terminal and uploading a file. The file gets uploaded but software crashes each time.

I use SSH connection to the server and open FTP session from within the connection through "Open secure file transfer"

**Comment by antenore** [comment]
Thanks for the report.
I've identified the issue. 
I'd fix it in the next days and hopefully we will release a new version in one or two weeks.

**Comment by antenore** [comment]
I've pushed a commit that is a temporary fix.
Remmina was crashing because I was freeing ssh->passphrase that is not yet correctly used in the sftp client. 
In the future I'll work on the sftp part as I've done for the SSH plugin and I'll fix all of the issues around the ssh passphrase.

@giox069 Are you agree regarding this temporary fix? ssh-passphrase? It's freed before to be used anyway and we should not have any strange case were ssh-passphrase already holds a value.

**Comment by antenore** [comment]
This week or the next we will release a new version of remmina with the fix
