### ISSUE TITLE
no rdp in the window option and no remmina command available in terminal

### ISSUE THREAD

**Issue by boistordu** [FreeRDP/Remmina#1302]
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): debian 9 stretch in qubesOS
* Remmina version (remmina --version): 1.2.0-rcgit-20
* Desktop environment (GNOME, Unity, KDE, ..):  don't know, not applicable
* Connecting to (OS and version):  
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 
no rdp in the list of options. 
no remmina shortcut in bash after all the ln sync work.

**Comment by boistordu** [comment]
you shouldnt' put the ln in /usr/local/bin but in /usr/bin 
that's more like it to work

still RDP ooption

**Comment by giox069** [comment]
There are no precompiled package for Debian 9. Which ,deb packages are you using?

**Comment by boistordu** [comment]
none i've compiled with your wiki

**Comment by giox069** [comment]
Every linux distribution, include Debian, has /usr/local/bin in the PATH, so when you type "remmina" it should work. Try to reboot your PC and see if it changes.
If it does not work after reboot, type the following commands on a terminal and copy&paste the output here
```
ls -la /usr/local/bin
ls -la /opt/remmina_devel
ldd /usr/local/bin/remmina
```
About the icon: the compilation instructions are for developers/tester. Desktop integration is another matter and should be done manually. You can try to copy the desktop file to the appropiate place, but I'm not shure if it works or not.
```
sudo cp /opt/remmina_devel/remmina/share/applications/*.desktop /usr/share/applications/
```

**Comment by boistordu** [comment]
im under qubesOS 
but anyway as I said it s not that the problem anymore isnce i've added another symbolic link to /usr/bin 

Heree the problem is the integration between RDP and remina

**Comment by boistordu** [comment]
So let's take to the ground level, how the freerdp integration is done in remmina?

**Comment by boistordu** [comment]
I guess it's not by a symbolic link? Because if it is it s a really shitty way to do it in place of doing some library in it

**Comment by antenore** [comment]
You just cannot install Remmina on top of Qubes OS as you are doing, before of playing with the internals of Qubes OS, that is an amazing OS, you should learn the basics of developing software on a Unix like OS.

I kindly advice you to test Remmina on a supported OS.

I'm closing this because it's not a bug report, if you need help on Qubes OS you can try posting on reddit (r/Qubes) or their Facebook page.

**Comment by boistordu** [comment]
I think you don't understand what I did....
First I've asked you a simple question: how FreeRDP is implemented or linked in Remmina?
Second, I'm not installing remmina on top of QubesOs but in a debian 9 template. 
Fact is that /usr/loca/bin/ doesn't proper link in bash to a auto completion command
But that's a marginal problem. 
The real problem here is how is FreeRDP is linked to Remmina since I don't see it in the list ?

**Comment by boistordu** [comment]
So Before to interpretate something that's not accurate , please do ask question...
And For your information I've tested the same thing in a totally different debian virtualmachine on another host and I have the same result so .... ?

**Comment by boistordu** [comment]
Plus it's totally out of range and you are saying just something absurd, we don't and we never do because we can't besides by tricky things, install something on top of QubesOS

**Comment by antenore** [comment]
I've got what you have tried to do, but still we cannot try to help you if you don't provide traces/logs/output of what you have done and the errors you have encountered so far. 

The FreeRDP libraries are dynamically linked to Remmina during the compilation time, so if you read the compilation output, you'll probably find that Remmina cannot find the FreeRDP package, why? Because you din't execute the ldconfig command? Nor you didn't install FreeRDP? Did you test xfreerdp, does it works? Anything else didn't work in the compilation, installation time? If you just cut&paste commands from the wiki, it won't work for sure..

How can we help you if you don't give us all the informations we need? That's the reason why I've closed this.

There's not any "shitty link" or whatever problem anyway.

If the Debian version you have used it's one of the latest (I don't remember the codename by hurt) , you won't be able to compile it easily, that could be another issue... 

etc, etc, etc

**Comment by boistordu** [comment]
Great finally something constructive. So you've based your code on a link during the compilation, finally we go forward.

Okey I've not noticed any error during the compilation which is kinda odd. 
I've test it FreeRDP before to compile the remmina source and it worked, kinda, it told me an error when I've tried to auth me on a windows server 2016 so I was guessing it was a problem with my password maybe or something else but not about the compilation itself. 
and after compilation remmina worked too without noticeable error (besides the gtk error that we always get which is just marginal).

The only influence since qubesOS is a virtualization distribution and so everything you launch is actually a VM, could IMO maybe the symbolic link around the private partition that every VM does have. But As I said I had the same problem another debian VM under kvm so this is why I was asking how it is implemented to determine if it is problem on my protocol. But again, IMO a lib .so in the compilation of remmina would be best to have a whole in one package but nevermind.

I will redo the vm and rerun the compilation and give you a look on the compilation log. 

could you in the same time, point to me which line in the log would be something like "missing path for xfreerdp" in the launch of remmina for example? Or something similar?

**Comment by antenore** [comment]
You will see at the end of the cmake phase while compiling remmina.
We don't use directly the xfreerdp binary, but the FreeRDP libraries.

**Comment by boistordu** [comment]
I think in 2 or 3 days or so I will have the possibility to really test it and give you some results.

**Comment by boistordu** [comment]
It worked. 
So I think it's publishing step of the lib directory that went wrong the first time. 
And I have made that mistake I think because I've wrongly understood your wiki. the part "for Ubuntu x64" at step 7.... it's the same thing on debian but I thought you were saying that to prevent to use that line but just to give us the example of ubuntu.
thanks for the help anyway.

**Comment by antenore** [comment]
Cool! Good to here it.
If you want you're free to improve the wiki.
We're not English mother tongue, so we make mistakes.
