### ISSUE TITLE
Unable to connect to RDP server

### ISSUE THREAD

**Issue by kstenerud** [FreeRDP/Remmina#1430]
* Client (OS name and version): GalliumOS 2.1
* Remmina version (remmina --version): 1.2.0-rcgit-26 (git rcgit-26)
* Desktop environment (GNOME, Unity, KDE, ..): LXDE
* Connecting to (OS and version): Windows 10
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): Doesn't exist

    $ xfreerdp
    bash: xfreerdp: command not found
    $ sudo find / -name xfreerdp
    $

I can't get remmina to connect to my windows 10 machine anymore. It worked for awhile, but now it just says "Unable to connect to RDP server".

* Remmina can still connect to my other linux desktops over RDP.
* I can still connect to Windows 10 from this machine using rdesktop from the shell.

I've tried following instructions in https://github.com/FreeRDP/Remmina/issues/1186 but there is no ~/.freerdp directory, and when I run remmina from the shell, there's no output at all. It forks and detaches, and that's it. The debug window shows nothing. Nothing in /var/log, either.

**Comment by giox069** [comment]
Before running remmina on the terminal, be sure to kill all running instances of remmina with "killall remmina". The immediate exit can be caused by an existing remmina process.
After running remmina again, it should not exit and you should see text output. Copy and paste here all the text, but after a failed connection.
How did you get remmina? Via the PPA ?

**Comment by kstenerud** [comment]
Ah there we go, got the output. Turns out that my saved password somehow got changed. Typed it in again and it works :)

**Comment by ic3d** [comment]
Hi @kstenerud we're reviewing old open issues. Do you still get this one? Thanks!
