### ISSUE TITLE
menu rdp, vnc, ssh not entirely visible and need stay clic to choose

### ISSUE THREAD

**Issue by florentlagoda** [FreeRDP/Remmina#1562]
* Client (OS name and version): Xubuntu Bionic 18.04 Beta 2 LTS
* Remmina version (remmina --version): 1.2.0-rcgit-29 (git rcgit-29)
* Desktop environment (GNOME, Unity, KDE, ..): XFCE (with Numix style and Numix circle icons)
* Connecting to (OS and version): /
* Connecting via (RDP, VNC, ...): /
* RDP issues only, freerdp version (xfreerdp --version): /

Hi,
Not critical but menu/list rdp, vnc, ssh not entirely visible

See screenshot here : http://imgur.com/UgFn3Xgl.png

**Comment by antenore** [comment]
Bonsoir Florent,

Thank you for the report.

Unlucky we can't do anything because this is a theme issue and not a Remmina issue, if you choose one of the default theme the text inside the combox is visible.

Probably it's enough you change the default font size and type, but I'm not an expert.

Consider to contact the Numix theme maintainers  https://github.com/numixproject/numix-gtk-theme or to post this same question on some Q&A site.

:-\ really sorry we cannot do anything for this.

**Comment by florentlagoda** [comment]
ok that's what seemed to me.
