### ISSUE TITLE
GTK2 branch

### ISSUE THREAD

**Issue by lahwaacz** [FreeRDP/Remmina#1567]
https://github.com/FreeRDP/Remmina/wiki#current-status says that there is a `gtk2` branch but it does not exist: https://github.com/FreeRDP/Remmina/branches/all

**Comment by antenore** [comment]
@lahwaacz I've removed that branch but I forgot to update the wiki.

We are not going to reintegrate it because it has diverged too much form the other branches.

Moreover we are going to reorganize the code and having a clean state is better.

If you need it for your personal use, you can clone one of the forked repository, I'm sure there tens of those that still have the GTK2 branch.
