### ISSUE TITLE
Do you plan to release for Windows? If proxy settings are configurable it will kill native RDP

### ISSUE THREAD

**Issue by drweb86-work** [FreeRDP/Remmina#1589]
Do you plan to release for Windows? 
If proxy settings are configurable it will kill native RDP

**Comment by antenore** [comment]
Thanks @drweb86-work for asking.

Not in the short term except if a contributor will work on this.

There's quite a lot of job to do, even if it's feasible and at the moment we are busy with a ton of other work to do.

The biggest challenges are around those functions that relay on the X11 eco system.

Beside that, even if I'm a *nix fanatic, I think that the Microsoft RDP client is still much better than Remmina, sure they should keep an eye on us as we have some few sweet functionalities that they should consider ;-)  

If you think it would be worth it, you can keep this issue opened and maybe reformulate a bit both the title and the body so that it looks more  like a feature request.

Thanks for bringing this up anyway.

**Comment by antenore** [comment]
BTW, we know about an happy Remmina user under windows through Cygwin

https://onedrive.live.com/?authkey=%21AEaxqP1mtwVLNac&id=8D68EF5FB06565C0%21446215&cid=8D68EF5FB06565C0 

https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fremmina%2Fremmina-1.2.0-0.9.rcgit.29&grep=remmina

**Comment by antenore** [comment]
Closing as answered.

**Comment by drweb86-work** [comment]
Thanks

**Comment by antenore** [comment]
@drweb86-work can you reformulate the proxy part of your question?
Maybe we can work on that or we already something that can help.
