### ISSUE TITLE
Problem connecting to Microsoft Terminal server via RDP

### ISSUE THREAD

**Issue by philnewby** [FreeRDP/Remmina#1635]
## Local System Description
* Client (ubuntu 18): edit: Ubuntu 16.04
* Remmina version ( `1.2.0-rcgit-24 (git rcgit-24)` ):
* Installation mean:
  - [X] Distribution package.
  - [ ] PPA.
  - [ ] Snap.
  - [ ] Flatpak.
  - [ ] Compiled from sources.
  - [ ] Other - detail:
* Desktop environment (GNOME, Unity, KDE, ..):
* Plugin:
  - [X] RDP - freerdp version ( ```xfreerdp --version``` ):
  - [ ] VNC
  - [ ] SSH
  - [ ] SFTP
  - [ ] SPICE
  - [ ] EXEC
  - [ ] Other (Please specify):

## Remote System Description

* Server (OS name and version): Windows Server 2012 R2 remote desktop server
* Special notes regarding the remote system (i.e. gateways, tunnel, etc): Digitally signed RDP file required

## Problem Description

My Remmina setup used to connect to my server perfectly well, but in the last month or so has stopped connecting with the message "Unable to Connect to RDP server"

Any ideas?

**Comment by sebaquadri** [comment]
You are not alone my friend. I'm having the same issue as you described above. Hopefully someine could give us a hand.

**Comment by weberhofer** [comment]
I'm quiet sure it's related to FreeRDP/Freerdp#4483

**Comment by giox069** [comment]
The version of remmina you reported, `1.2.0-rcgit-24` is not the one provided by Ubuntu 18.04.
You should have `1.2.0-rcgit-29` on ubnut 18.04.
I think you have some old packages or binaries that need to be removed, both of remmina and freerdp2.
Try to remove all remmina and freerdp packages and reinstall it.

**Comment by sebaquadri** [comment]
Hi my friend... I did follow these steps below...(https://github.com/FreeRDP/Remmina/wiki)


==============================

For Ubuntu users we have an official PPA with Remmina 1.2

https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next<https://launchpad.net/%7Eremmina-ppa-team/+archive/ubuntu/remmina-next>

To install it, just copy and paste the following three lines on a terminal window

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp remmina-plugin-secret


Don't forget to exit/kill al your running instances of remmina. The best way to do it is to reboot your PC. Or, if you cannot reboot, kill all running remmina with

sudo killall remmina


==============================


But I'm still getting the same error and the following messages:


sebaquadri@sebaquadri-VirtualBox:~$ remmina
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:2633): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(remmina:2633): GLib-CRITICAL **: g_key_file_set_string: assertion 'string != NULL' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[10:41:36:787] [2633:2728] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[10:41:36:787] [2633:2728] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[10:41:36:787] [2633:2728] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[10:41:36:787] [2633:2728] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[10:41:37:145] [2633:2728] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[10:41:37:145] [2633:2728] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[10:41:37:145] [2633:2728] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[10:41:37:145] [2633:2728] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Tried changing on "Advanced"-"Security" from RDP to TLS but the same error. No luck.


Sebastián José Quadri
Analista de Sistemas de Computación
Symantec Certified Specialist
Mobile: +54 9 351 6744661
e-mail: sebaquadri@hotmail.com

____________________________________________________________________________

Save Nature! - Please don't print this e-mail unless you really need to.
Cuide la Naturaleza! - Por favor no imprima este e-mail salvo que realmente lo necesite.


________________________________
De: Giovanni Panozzo <notifications@github.com>
Enviado: viernes, 18 de mayo de 2018 11:08 a.m.
Para: FreeRDP/Remmina
Cc: Sebastian; Comment
Asunto: Re: [FreeRDP/Remmina] Problem connecting to Microsoft Terminal server via RDP (#1635)


The version of remmina you reported, 1.2.0-rcgit-24 is not the one provided by Ubuntu 18.04.
You should have 1.2.0-rcgit-29 on ubnut 18.04.
I think you have some old packages or binaries that need to be removed, both of remmina and freerdp2.
Try to remove all remmina and freerdp packages and reinstall it.

**Comment by giox069** [comment]
Please type the following commands and paste the output here of each command:
```
killall remmina                   (output not needed here ;))
apt-cache policy remmina
which remmina
remmina --full-version
ldd /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so  | fgrep freerdp
dpkg --list "freerdp*"
```
then, after doing that, uninstall all packages
```
sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"
```
and reinstall
```
sudo apt-get install remmina remmina-plugin-rdp remmina-plugin-secret
```
reboot and then recheck the remmina version:
```
remmina --version
```
retry to connect and report here.

**Comment by giox069** [comment]
Also please set "Security" to "Negotiate" in all your tests, thank you.

**Comment by sebaquadri** [comment]
Rebooting now... I'll get back to you with remmina version after reboot...


Commands outputsso far...


sebaquadri@sebaquadri-VirtualBox:~$ killall remmina
sebaquadri@sebaquadri-VirtualBox:~$ sudo su -
[sudo] password for sebaquadri:
root@sebaquadri-VirtualBox:~# killall remmina
remmina: no process found
root@sebaquadri-VirtualBox:~# apt-cache policy remmina
remmina:
  Installed: 1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1
  Candidate: 1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1
  Version table:
 *** 1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1 500
        500 http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.2-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
root@sebaquadri-VirtualBox:~# which remmina
/usr/bin/remmina
root@sebaquadri-VirtualBox:~# remmina --full-version
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
WARNING: Remmina is running with a secret plugin, but it cannot connect to a secret service.
Remmina - 1.2.0-rcgit-29 (git rcgit-29)
NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev2 (git n/a)
RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev2 (git n/a)
RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.2.0-rcgit-29 (git rcgit-29), FreeRDP lib: 2.0.0-dev2 (git n/a)
SFTP                Protocol        SFTP - Secure File Transfer                                     1.2.0-rcgit-29
SSH                 Protocol        SSH - Secure Shell                                              1.2.0-rcgit-29
VNC                 Protocol        VNC - Virtual Network Computing                                 1.2.0-rcgit-29
glibsecret          Secret          GNOME libsecret                                                 1.2.0-rcgit-29
root@sebaquadri-VirtualBox:~# ldd /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so  | fgrep freerdp
    libfreerdp2.so.2 => /usr/lib/x86_64-linux-gnu/libfreerdp2.so.2 (0x00007fc667f41000)
    libfreerdp-client2.so.2 => /usr/lib/x86_64-linux-gnu/libfreerdp-client2.so.2 (0x00007fc667ce0000)
root@sebaquadri-VirtualBox:~# dpkg --list "freerdp*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
+++-====================================-=======================-=======================-=============================================================================
un  freerdp-x11                          <none>                  <none>                  (no description available)
root@sebaquadri-VirtualBox:~# sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'remmina-plugin-nx' for glob 'remmina*'
Note, selecting 'remmina-xfce' for glob 'remmina*'
Note, selecting 'remmina-gnome' for glob 'remmina*'
Note, selecting 'remmina-plugin-telepathy' for glob 'remmina*'
Note, selecting 'remmina-plugin-data' for glob 'remmina*'
Note, selecting 'remmina-common' for glob 'remmina*'
Note, selecting 'remmina-plugin-exec' for glob 'remmina*'
Note, selecting 'remmina' for glob 'remmina*'
Note, selecting 'remmina-plugin-gnome' for glob 'remmina*'
Note, selecting 'remmina-plugin-xdmcp' for glob 'remmina*'
Note, selecting 'remmina-plugin-spice' for glob 'remmina*'
Note, selecting 'remmina-plugin-rdp' for glob 'remmina*'
Note, selecting 'remmina-dbg' for glob 'remmina*'
Note, selecting 'remmina-plugin-secret' for glob 'remmina*'
Note, selecting 'remmina-plugin-vnc' for glob 'remmina*'
Package 'remmina-plugin-data' is not installed, so not removed
Package 'remmina-gnome' is not installed, so not removed
Package 'remmina-xfce' is not installed, so not removed
Note, selecting 'libfreerdp-codec1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-locale1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-gdi1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-crypto1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-common1.1.0' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-core1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp1-dbg' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-utils1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-cache1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-rail1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-client2' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-client1.1' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-plugins-standard' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-plugins-standard-dbg' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-dbg' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-dev' for glob 'libfreerdp*'
Note, selecting 'libfreerdp-primitives1.1' for glob 'libfreerdp*'
Package 'libfreerdp-client2' is not installed, so not removed
Note, selecting 'libwinpr-bcrypt0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-environment0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-credentials0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-winsock0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-library0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-rpc0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-synch0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-timezone0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-handle0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-registry0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-interlocked0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-crt0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-sysinfo0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-io0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-asn1-0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-file0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-error0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-sspi0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-sspicli0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-dbg' for glob 'libwinpr*'
Note, selecting 'libwinpr-dev' for glob 'libwinpr*'
Note, selecting 'libwinpr-utils0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-dsparse0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-input0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-winhttp0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-heap0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-path0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-thread0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-pool0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-crypto0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-credui0.1' for glob 'libwinpr*'
Note, selecting 'libwinpr-pipe0.1' for glob 'libwinpr*'
Note, selecting 'freerdp-x11' for glob 'freerdp*'
Note, selecting 'freerdp-x11-dbg' for glob 'freerdp*'
Note, selecting 'freerdp' for glob 'freerdp*'
Note, selecting 'freerdp-x11' instead of 'freerdp'
Package 'remmina-plugin-gnome' is not installed, so not removed
Package 'libfreerdp-cache1.1' is not installed, so not removed
Package 'libfreerdp-client1.1' is not installed, so not removed
Package 'libfreerdp-codec1.1' is not installed, so not removed
Package 'libfreerdp-common1.1.0' is not installed, so not removed
Package 'libfreerdp-core1.1' is not installed, so not removed
Package 'libfreerdp-crypto1.1' is not installed, so not removed
Package 'libfreerdp-dbg' is not installed, so not removed
Package 'libfreerdp-gdi1.1' is not installed, so not removed
Package 'libfreerdp-locale1.1' is not installed, so not removed
Package 'libfreerdp-primitives1.1' is not installed, so not removed
Package 'libfreerdp-rail1.1' is not installed, so not removed
Package 'libfreerdp-utils1.1' is not installed, so not removed
Package 'libwinpr-asn1-0.1' is not installed, so not removed
Package 'libwinpr-bcrypt0.1' is not installed, so not removed
Package 'libwinpr-credentials0.1' is not installed, so not removed
Package 'libwinpr-credui0.1' is not installed, so not removed
Package 'libwinpr-crt0.1' is not installed, so not removed
Package 'libwinpr-crypto0.1' is not installed, so not removed
Package 'libwinpr-dbg' is not installed, so not removed
Package 'libwinpr-dev' is not installed, so not removed
Package 'libwinpr-dsparse0.1' is not installed, so not removed
Package 'libwinpr-environment0.1' is not installed, so not removed
Package 'libwinpr-error0.1' is not installed, so not removed
Package 'libwinpr-file0.1' is not installed, so not removed
Package 'libwinpr-handle0.1' is not installed, so not removed
Package 'libwinpr-heap0.1' is not installed, so not removed
Package 'libwinpr-input0.1' is not installed, so not removed
Package 'libwinpr-interlocked0.1' is not installed, so not removed
Package 'libwinpr-io0.1' is not installed, so not removed
Package 'libwinpr-library0.1' is not installed, so not removed
Package 'libwinpr-path0.1' is not installed, so not removed
Package 'libwinpr-pipe0.1' is not installed, so not removed
Package 'libwinpr-pool0.1' is not installed, so not removed
Package 'libwinpr-registry0.1' is not installed, so not removed
Package 'libwinpr-rpc0.1' is not installed, so not removed
Package 'libwinpr-sspi0.1' is not installed, so not removed
Package 'libwinpr-sspicli0.1' is not installed, so not removed
Package 'libwinpr-synch0.1' is not installed, so not removed
Package 'libwinpr-sysinfo0.1' is not installed, so not removed
Package 'libwinpr-thread0.1' is not installed, so not removed
Package 'libwinpr-timezone0.1' is not installed, so not removed
Package 'libwinpr-utils0.1' is not installed, so not removed
Package 'libwinpr-winhttp0.1' is not installed, so not removed
Package 'libwinpr-winsock0.1' is not installed, so not removed
Package 'libfreerdp-dev' is not installed, so not removed
Package 'freerdp-x11' is not installed, so not removed
Package 'remmina-plugin-nx' is not installed, so not removed
Package 'remmina-plugin-xdmcp' is not installed, so not removed
Package 'remmina-plugin-telepathy' is not installed, so not removed
Package 'freerdp-x11-dbg' is not installed, so not removed
Package 'libfreerdp-plugins-standard-dbg' is not installed, so not removed
Package 'remmina-dbg' is not installed, so not removed
Package 'libfreerdp1-dbg' is not installed, so not removed
Package 'remmina-plugin-spice' is not installed, so not removed
Package 'remmina-plugin-exec' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  i965-va-driver libavahi-ui-gtk3-0 libavcodec-ffmpeg56 libavutil-ffmpeg54 libcrystalhd3 libgsm1 libmp3lame0 libopenjpeg5 libschroedinger-1.0-0 libshine3 libsnappy1v5
  libsoxr0 libssh-4 libswresample-ffmpeg1 libtwolame0 libva1 libvncclient1 libx264-148 libx265-79 libxvidcore4 libzvbi-common libzvbi0 mesa-va-drivers va-driver-all
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  libfreerdp-plugins-standard* libfreerdp1* remmina* remmina-common* remmina-plugin-rdp* remmina-plugin-secret* remmina-plugin-vnc*
0 upgraded, 0 newly installed, 7 to remove and 6 not upgraded.
After this operation, 5,360 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 469179 files and directories currently installed.)
Removing remmina-plugin-rdp (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Removing remmina-plugin-secret (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Removing remmina-plugin-vnc (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Removing remmina (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Purging configuration files for remmina (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Removing remmina-common (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Removing libfreerdp-plugins-standard:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Removing libfreerdp1:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
root@sebaquadri-VirtualBox:~# sudo apt-get install remmina remmina-plugin-rdp remmina-plugin-secret
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libfreerdp-plugins-standard libfreerdp1 remmina-common remmina-plugin-vnc
Suggested packages:
  freerdp-x11
The following NEW packages will be installed:
  libfreerdp-plugins-standard libfreerdp1 remmina remmina-common remmina-plugin-rdp remmina-plugin-secret remmina-plugin-vnc
0 upgraded, 7 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/1,457 kB of archives.
After this operation, 5,360 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package libfreerdp1:amd64.
(Reading database ... 468982 files and directories currently installed.)
Preparing to unpack .../libfreerdp1_2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1_amd64.deb ...
Unpacking libfreerdp1:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Selecting previously unselected package libfreerdp-plugins-standard:amd64.
Preparing to unpack .../libfreerdp-plugins-standard_2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1_amd64.deb ...
Unpacking libfreerdp-plugins-standard:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Selecting previously unselected package remmina-common.
Preparing to unpack .../remmina-common_1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1_all.deb ...
Unpacking remmina-common (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Selecting previously unselected package remmina.
Preparing to unpack .../remmina_1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1_amd64.deb ...
Unpacking remmina (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Selecting previously unselected package remmina-plugin-rdp.
Preparing to unpack .../remmina-plugin-rdp_1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1_amd64.deb ...
Unpacking remmina-plugin-rdp (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Selecting previously unselected package remmina-plugin-secret.
Preparing to unpack .../remmina-plugin-secret_1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1_amd64.deb ...
Unpacking remmina-plugin-secret (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Selecting previously unselected package remmina-plugin-vnc.
Preparing to unpack .../remmina-plugin-vnc_1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1_amd64.deb ...
Unpacking remmina-plugin-vnc (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up remmina-common (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Setting up remmina (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Setting up remmina-plugin-secret (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Setting up remmina-plugin-vnc (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Setting up libfreerdp1:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Setting up libfreerdp-plugins-standard:amd64 (2.0.0~git201804050820-0+remmina201804082033.ra9ecd6a.d9be5820~ubuntu16.04.1) ...
Setting up remmina-plugin-rdp (1.2.0-rcgit-29-0~remmina201804082058.r6b62986.d3c469a0~ubuntu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
root@sebaquadri-VirtualBox:~#



Sebastián José Quadri
Analista de Sistemas de Computación
Symantec Certified Specialist
Mobile: +54 9 351 6744661
e-mail: sebaquadri@hotmail.com

____________________________________________________________________________

Save Nature! - Please don't print this e-mail unless you really need to.
Cuide la Naturaleza! - Por favor no imprima este e-mail salvo que realmente lo necesite.


________________________________
De: Giovanni Panozzo <notifications@github.com>
Enviado: viernes, 18 de mayo de 2018 01:56 p.m.
Para: FreeRDP/Remmina
Cc: Sebastian; Comment
Asunto: Re: [FreeRDP/Remmina] Problem connecting to Microsoft Terminal server via RDP (#1635)


Please type the following commands and paste the output here of each command:

killall remmina                   (output not needed here ;))
apt-cache policy remmina
which remmina
remmina --full-version
ldd /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so  | fgrep freerdp
dpkg --list "freerdp*"


then, after doing that, uninstall all packages

sudo apt purge "remmina*" "libfreerdp*" "libwinpr*" "freerdp*"


and reinstall

sudo apt-get install remmina remmina-plugin-rdp remmina-plugin-secret


reboot and then recheck the remmina version:

remmina --version


retry to connect and report here.

**Comment by giox069** [comment]
Also add the output of
```
cat /etc/lsb-release
```

**Comment by sebaquadri** [comment]
sebaquadri@sebaquadri-VirtualBox:~$ sudo remmina --version
[glibsecret] unable to get secret service: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
Plugin entry returned false: /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-secret.so.
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
WARNING: Remmina is running with a secret plugin, but it cannot connect to a secret service.
Remmina - 1.2.0-rcgit-29 (git rcgit-29)
sebaquadri@sebaquadri-VirtualBox:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
sebaquadri@sebaquadri-VirtualBox:~$



Sebastián José Quadri
Analista de Sistemas de Computación
Symantec Certified Specialist
Mobile: +54 9 351 6744661
e-mail: sebaquadri@hotmail.com

____________________________________________________________________________

Save Nature! - Please don't print this e-mail unless you really need to.
Cuide la Naturaleza! - Por favor no imprima este e-mail salvo que realmente lo necesite.


________________________________
De: Giovanni Panozzo <notifications@github.com>
Enviado: viernes, 18 de mayo de 2018 02:20 p.m.
Para: FreeRDP/Remmina
Cc: Sebastian; Comment
Asunto: Re: [FreeRDP/Remmina] Problem connecting to Microsoft Terminal server via RDP (#1635)


Also add the output of

cat /etc/lsb-release

**Comment by sebaquadri** [comment]
Still getting errors....


sebaquadri@sebaquadri-VirtualBox:~$ remmina
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:2602): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[12:26:19:270] [2602:2645] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[12:26:19:270] [2602:2645] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[12:26:19:270] [2602:2645] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:26:19:270] [2602:2645] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[12:26:19:651] [2602:2645] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[12:26:19:651] [2602:2645] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[12:26:19:651] [2602:2645] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[12:26:19:651] [2602:2645] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.





Sebastián José Quadri
Analista de Sistemas de Computación
Symantec Certified Specialist
Mobile: +54 9 351 6744661
e-mail: sebaquadri@hotmail.com

____________________________________________________________________________

Save Nature! - Please don't print this e-mail unless you really need to.
Cuide la Naturaleza! - Por favor no imprima este e-mail salvo que realmente lo necesite.


________________________________
De: Giovanni Panozzo <notifications@github.com>
Enviado: viernes, 18 de mayo de 2018 02:20 p.m.
Para: FreeRDP/Remmina
Cc: Sebastian; Comment
Asunto: Re: [FreeRDP/Remmina] Problem connecting to Microsoft Terminal server via RDP (#1635)


Also add the output of

cat /etc/lsb-release

**Comment by giox069** [comment]
Have you reset "Advanced->Security" to "Negotiate" in the profile settings?

**Comment by sebaquadri** [comment]
It is working now! Thank you very much for your help and time dedicated to resolve this issue. Have a great day ahead!


Sebastián José Quadri
Analista de Sistemas de Computación
Symantec Certified Specialist
Mobile: +54 9 351 6744661
e-mail: sebaquadri@hotmail.com

____________________________________________________________________________

Save Nature! - Please don't print this e-mail unless you really need to.
Cuide la Naturaleza! - Por favor no imprima este e-mail salvo que realmente lo necesite.


________________________________
De: Giovanni Panozzo <notifications@github.com>
Enviado: sábado, 19 de mayo de 2018 07:11 p.m.
Para: FreeRDP/Remmina
Cc: Sebastian; Comment
Asunto: Re: [FreeRDP/Remmina] Problem connecting to Microsoft Terminal server via RDP (#1635)


Have you reset "Advanced->Security" to "Negotiate" in the profile settings?

**Comment by giox069** [comment]
You're welcome.
