### ISSUE TITLE
FTBS 1.0.0 :  ld - undefined reference to symbol 'g_module_symbol' -- links.txt missing necessary libraries

### ISSUE THREAD

**Issue by Corin-EU** [FreeRDP/Remmina#182]
PRETTY_NAME="Ubuntu quantal (12.10)"
VERSION="12.10, Quantal Quetzal"

The cmakefile rules fail to generate a links.txt file with all of the necessary libraries specified for successful linking on both i386 and x86_64 Mint Nadia14/Ubuntu 12.10

[ 33%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_widget_pool.c.o
Linking C executable remmina
/usr/bin/ld: CMakeFiles/remmina.dir/src/remmina_plugin_manager.c.o: undefined reference to symbol 'g_module_symbol'
/usr/bin/ld: note: 'g_module_symbol' is defined in DSO /usr/lib/i386-linux-gnu/libgmodule-2.0.so.0 so try adding it to the linker command line
/usr/lib/i386-linux-gnu/libgmodule-2.0.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

Adding the necessary libraries

 -lgmodule-2.0 -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lX11 -lpthread

between -lglib-2.0 and  -lpango-1.0 in the generated file

remmina/CMakeFiles/remmina.dir/links.txt

results in a successful linking and creation of the remmina executable.

Please would you review the CMakeFile dependency rules to ensure that these required libraries are included automatically in links.txt during the CMakeFile generation process.

**Comment by frankzeka** [comment]
voler88, I cannot find the remmina.dir. I have the same error of autmnapprentice.

**Comment by giox069** [comment]
This issue is more than 2 years old, a lot of things are changed in the meanwhile, including remmina cmake files for finding the pthread library.
Please reopen another issue, and don't forget to tell us which operating system you are using, which distribution, which version of the OS and remmina, and which desktop environment. Also please take a look at the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for info on compiling.
Also please paste the text of the compiler output which contains the error when you will open the new issue.
