### ISSUE TITLE
Can't execute the last GIT with GTK2 (undefined symbol: gdk_pixbuf_get_from_surface)

### ISSUE THREAD

**Issue by Kal42** [FreeRDP/Remmina#220]
Hello,

I have an issue with the last git version when I use GTK2.

In file : remmina-plugins/rdp/rdp_event.c
Line 688 :  pixbuf = gdk_pixbuf_get_from_surface(surface, 0, 0, pointer->width, pointer->height);

This function does not exist in GTK2

And when you run a rdp the error is 
remmina: symbol lookup error: /usr/lib/remmina/plugins/remmina-plugin-rdp.so: undefined symbol: gdk_pixbuf_get_from_surface

**Comment by mike-pt** [comment]
I've come up to this issue after installing the freebsd port...

In the Makefile I see:
``` 
USES=           cmake gmake pkgconfig
USE_GNOME=      atk gdkpixbuf2 glib20 gtk20 pango
INSTALLS_ICONS= yes
LDFLAGS+=       -L${LOCALBASE}/lib ${PTHREAD_LIBS} -Wl,-rpath -Wl,${LOCALBASE}/lib -lX11 \
                -lgio-2.0 -lgobject-2.0 -lgthread-2.0 -lgmodule-2.0 -lgtk-x11-2.0
CPPFLAGS+=      -I${LOCALBASE}/include ${PTHREAD_CFLAGS}
CFLAGS+=        -I${WRKSRC}/remmina/include -I${LOCALBASE}/include ${PTHREAD_CFLAGS} -fPIC
```

I could change gtk20 to gtk30 but what about the rest? Do any of this flags make sense in the latest version from git?

**Comment by muflone** [comment]
here we have three different branches:
**master** is the stable version, built for GTK+ 3
**gtk2** is the stable version, built for GTK+ 2
**next** is the development version, built for GTK+ 3

what branch are you trying to build?

**Comment by mike-pt** [comment]
Good question, the ports system grabs the tar.gz from the releases, so in this case it would be:
Pre-release
 v1.2.0-rcgit.2
 93bf25e

Is this one the same as master at this point?

I've tried the following changes in the Makefile:
-USE_GNOME=     atk gdkpixbuf2 glib20 gtk20 pango
+USE_GNOME=     atk gdkpixbuf2 glib20 gtk30 pango
(This is specific to the ports system, but I just need to know If I do need those dpendencies or not... and maybe more in the new version?


Also I see this in the Makefile:
```
 # now cannot build with gtk30 because requisite ports are old`<------
-CMAKE_ARGS+=   -DGTK_VERSION=2
+CMAKE_ARGS+=   -DGTK_VERSION=3 -DWITH_APPINDICATOR=OFF
```

I'm still trying with GTK_VERSION=3 but it will probably fail, I added "-DWITH_APPINDICATOR=OFF" because I couldn't find appindicator in ports.

Also this patch seems outdated, at least Cmakelists.txt I will have a look and try to build
https://github.com/freebsd/freebsd-ports/blob/master/net/remmina/files/patch-FreeRDP-Remmina-b6a55ae

**Comment by giox069** [comment]
v1.2.0-rcgit.2 is the current "next" branch, the more "advanced" one in remmina. It needs FreeRDP 1.2 to be compiled, and works only with GTK3. You can safely disable appindicator library.

Also please note that you are talking about FreeBSD specific issues: we do not have USE_GNOME in Makefile. Makefiles are dynamically generated with cmake command (and CMakeLists.txt)... I'm a bit confused with FreeBSD, because I do not use it. Where does your Makefile comes from ?

A little thing that can confuse an automatic build system: you said "the ports system grabs the tar.gz from the releases". We interleave releases of version 1.1.X, 1.2.X and maybe 1.1.X(gtk)... could this be a problem ?

**Comment by mike-pt** [comment]
Yes that was FreeBSD specific the ports have there own Makefile basicly all I wanted to know was if those libs make sense the USE_GNOME simple means a certain gnome lib is needed, and so it gets it from the ports tree... (more info here: https://www.freebsd.org/gnome/docs/porting.html if you're interested).

I'm just trying to fix the port in my local version and some insight on what dependencies do I need might be useful. Or for example confirmation that "appindicator" can be disabled (thanks).

The sable version on ports is building 1.0 it seems:
GH_COMMIT=      356c033 

But with that one I get the RDP issue, which is why I'm trying to see If I get it to build with gtk3, but if I can build it with gtk2 and avoid the "undefined symbol: gdk_pixbuf_get_from_surface" I'll still be happy.

**Comment by giox069** [comment]
Switching to issue #431, since this is no longer GTK2 related.

**Comment by antenore** [comment]
Closing as outdate. @mike-pt we have adapted the Remmina to compile on FreeBSD, but port is not using the last code base. If you know someone who can help with port I'm willing to support them
