### ISSUE TITLE
[BUG] RDP Preferences don't saving

### ISSUE THREAD

**Issue by sheynandr** [FreeRDP/Remmina#391]
Hi. I'm change rdp quality to max in preferences, but them not saving. Also i'm create a new rdp connection, change quality to max, but desktop wallpaper not showing in remote connection.

**Comment by Neldogz** [comment]
I am also experiencing the same problems as the original user. Changes are not saving to neither global nor connection specific preferences. 

Linux computer1 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux
GNOME Shell 3.16.3 
Remmina version 1.1.2 - Installed from the official Arch repositories. 

Connecting to a Windows 7 64-bit host.

**Comment by giox069** [comment]
We cannot patch the arch reposiotries. Try to compile the latest version of remmina (1.2.X) by following the guide for arch in the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki)

**Comment by Neldogz** [comment]
Hi Giovanni,

Thank you for your note. I followed the directions per article: 
https://github.com/FreeRDP/Remmina/wiki/Compile-Remmina-on-Arch-Linux 
but unfortunately still cannot save preferences.

Best,
Nelson

**Comment by pyskell** [comment]
I think the issue here is that the settings are unclear.

At RDP > Quality settings you're actually setting what each level of quality means (ex. does "Poor" allow wallpaper?, is menu animation shown under "Medium"?). There is where you configure what each level means.

For each box you go to Edit Profile > Advanced and pick a level for "Quality".

So it works, just not the way expected. I'd suggest maybe adding a quality tab for each profile, have the Poor/Medium/Good/Best defaults but let people configure each one specifically.
