### ISSUE TITLE
RDP clipboard and shared folder issue

### ISSUE THREAD

**Issue by avoidik** [FreeRDP/Remmina#406]
Mint 17 x86_64
Remmina 1.2.0-rcgit.1
FreeRDP 1.2.0-beta1 (git 1.2.0-beta1+android9-244-gce17f)

1. Ensure RDP connection have set Shared folder and connect to a server
2. Inside RDP connection copy something to clipboard
3. Remmina freezes and became unresponsive with repeated error in console:
(remmina:4860): GLib-CRITICAL **: g_async_queue_push: assertion 'data' failed
4. killall remmina
5. Restart Remmina and unset Shared folder tick
6. Connect to RDP and copy something to clipboard
7. Everything ok
8. Close session, connect again. Copy something to clipboard. Freeze again.

**Comment by mmardegan** [comment]
Fedora 20 64bit, KDE 4.14.4, remmina 1.2.0-rcgit.2
------------
I installed the program using this guide: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20.
I can finally share also the smart card: thanks to all the developers!!!
But there is still a problem: when I try to share a folder in the configuration tab of a connection, the program crashes, with this error messages: 
------------
(remmina:10841): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed
(remmina:10841): GLib-GObject-WARNING **: gtype.c:4215: type id '0' is invalid
(remmina:10841): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Errore di segmentazione
------------
The problem was present also in the previous versions of remmina e kde.
Is there a way to resolve this issue?
Thank you very much.

**Comment by muflone** [comment]
@mmardegan please open a separated request for each issue
