### ISSUE TITLE
Unable to connect using \\server-name

### ISSUE THREAD

**Issue by mbnoimi** [FreeRDP/Remmina#435]
I tried to connect to Windows PC using RDP it works fine when I input server address as IP  (192.168.0.2) but it doesn't work when I input \\server-name OR server-name

**Comment by giox069** [comment]
Provided that your problem is a "name resolution" problem, and in Remmina this is totally delegated to the underlying operating system, here are some hints:
**\\\server-name** is a windows syntax and no linux application will understand it. I never heard of **\server-name**. The **server-name** only syntax will work only if you have correctly setup some kind of name resolution system for your local network.
There is no really simple way to do it: name resolution can happen in many different ways, but there is not a standard way supported out of the box by both windows and linux. It's strongly dependent on which ditributions, installed packages, windows versions you are using.
And... as said before, it's not a Remmina related issue.
