### ISSUE TITLE
Only one host key per domain name is allowed

### ISSUE THREAD

**Issue by realdreams** [FreeRDP/Remmina#465]
In practice, the same FQDN can run more than one terminal servers multiplexed by port numbers (for example, the FQDN is the public address on a NAT device). Once the first known host key is saved for the FQDN, all new RDP connections to the same FQDN but different port number will fail (and the error message does not say why).

They do not have to have the same host key.
rdp.example.com:3389
rdp.example.com:3390
rdp.example.com:3391

**Comment by giox069** [comment]
Which version of remmina are you using ? In which OS ? Please look at the [wiki](https://github.com/FreeRDP/Remmina/wiki) if you need to upgrade.

**Comment by realdreams** [comment]
0.9.99.1 shipped with Ubuntu trusty.
Looks like this is a FreeRDP bug, someone opened issue #465 under FreeRDP/FreeRDP

**Comment by giox069** [comment]
Follow the instructions at the top of the wiki home page and install the Ubuntu PPA for the "next" branch of remmina. This problem has already been fixed time ago, I think.

**Comment by giox069** [comment]
See also Remmina issue #373 (which is fixed and closed).

**Comment by realdreams** [comment]
Thanks very much. I confirm it has been fixed in 1.2.0-rcgit.2 on Ubuntu PPA.
Just curious why the GUI says 1.2.0-rcgit.2 but the package is named 1.1.1-1+673+next+201502141616~ubuntu14.04.1?

**Comment by giox069** [comment]
Remmina "next" (1.2) is not yet released as official: we are waiting for the people at FreeRDP to release FreeRDP 1.2 and we want to be aligned. Despite that, remmina-next it's stable enough to be used for everyday life. You may get some new bugs in the "next" PPA due to the development in progress, but usually they are fixed in few days.
I don't really know why of this naming in Ubuntu, because I'm not the maintainer of the PPA. I think it's a naming convention for ubuntu for packages not yet released, so when remmina 1.2 official will be released by us, he will upgrade to 1.2.
