### ISSUE TITLE
Missing controls tab from top/center of window in Gnome

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#481]
[ forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771784 ]

When I connect to a Windows Server using the RDP protocol, there is no "controls" tab at the top/center of the screen.  Thus I cannot easily return to my Linux desktop nor can I easily switch between multiple RDP connections to other Windows servers.

I see this bug in *Gnome* but not in the Xfce desktop environment.

**Comment by Hubbitus** [comment]
Our Fedora users report similar issues:
https://bugzilla.redhat.com/show_bug.cgi?id=1161096
https://bugzilla.redhat.com/show_bug.cgi?id=1173057

**Comment by giox069** [comment]
The "floating toolbar" works very bad under Gnome Shell. I wasted hours on trying to get it working, but Gnome Shell refuses to show it randomly, and some versions of Gnome Shell will also never route events to it. There should be some kind of problem between Gnome Shell and popup windows. In the future, Remmina will no longer use a popup window to display the floating toolbar, but it will be compatible only with GTK+3.10 or newer.
See the [https://github.com/FreeRDP/Remmina/wiki/Remmina-Usage-FAQ](Usage FAQ)

**Comment by Hubbitus** [comment]
Thank you @giox069. In Fedora we already have gtk3 3.14.9 in current stable version 21. Is there something what we already could try? May be patch or development branch?

**Comment by MoonSweep** [comment]
Same problem with v1.1.1 (Debian Jessie) on MATE desktop. I retitled the Debian bug mentioned by OP and added this info.

**Comment by giox069** [comment]
Just to update this issue:
The "fullscreen toolbar" has been completly changed in Remmina 1.2.0-rcgit3 ("next" branch), changing from a popup window to a GtkOverlay+GtkRevealer widget, available since GTK3.10.
The main pull request for the new toolbar is here: ttps://github.com/FreeRDP/Remmina/commit/726acdb7daa9c1e5b614a7ed6b3c2aa8b889169c and some subsequent minor fixes.
I could also backport this big change to Remmina 1.1.2 "master" branch, but it requires a certain amount of work. Will such a backport be useful for debian8 and/or fedora ?

**Comment by Hubbitus** [comment]
Thank you Giovanni. If it is not trivial to backport, I think it have no worth doing so for Fedora.

**Comment by MoonSweep** [comment]
More info : it seems to happen only when the display is scaled. I managed to find a temporary workaround to make the bar appear: switch to non-scaled (Ctrl_R+S) and the bar will appear, and it will stay even after switching back to scaled display; but the trick must be re-done after each connection. So maybe the fix won't need a full backport of the new widget, you only need to find why the bar doesn't appear in the first place and fix that.

**Comment by MoonSweep** [comment]
If it helps, I noticed last week that on a Jessie box with Gnome 3.14, the workaround mentioned above doesn't work: the toolbar doesn't appear at all (I usually use MATE but tried Gnome for a week).

**Comment by giox069** [comment]
1. Porting the commit https://github.com/FreeRDP/Remmina/commit/726acdb7daa9c1e5b614a7ed6b3c2aa8b889169c to remmina requires a certain amount of code change, so it needs a lot of testing. This will make remmina 1.1 "unstable", which is not.
2. I could also try to do the above work, but I don't think that distribution maintainers will integrate a newer remmina 1.1.3 in current stable distro. I don't think you will have it patched on Debian Jessie.
3. But I also recognize that patching that toolbar in Remmina 1.1 could be useful for the next stable version of distributions (i.e.: debian stretch). Will a newer Remmina 1.1.3 be welcomed in debian stretch ?

So the question for all people reading this message is: should I backport the "floating toolbar fix" from remmina 1.2 (commit https://github.com/FreeRDP/Remmina/commit/726acdb7daa9c1e5b614a7ed6b3c2aa8b889169c) to Remmina 1.1 and help next stable linux distributions releases to have a working remmina floating toolbar under Gnome ?

**Comment by dktrkranz** [comment]
From a Debian point of view, I doubt such a high-impact change would make into a point release for Jessie. I could create a backport if you consider a 1.1.3 release could be prepared.

I think the best option would be to wait for FreeRDP stable release (hopefully it will happen one day...), then release the newest and greatest Remmina with all the fixes and improvements. It won't make into Jessie officially, but Debian is considering to create "PPA's" similar to the Ubuntu ones, so we could backport both, and instruct users to point to the "PPA's"...

**Comment by MoonSweep** [comment]
IMHO it depends on when 1.2 will be available. As far as I know, ATM all major Linux distros suffer from the lack of a working VNC/RDP client (vinagre and virt-viewer suffer from the same "toolbar" problem (even worse because it doesn't appear at all), in addition of being awfully slow).

I think backporting the fix to 1.1 branch and building Jessie backports would be the best solution (why wait for Debian PPAs ? Looking at the discussions on debian-devel, they're far from ready... But we agree that such a change isn't likely to make it into a point release).

ATM Remmina 1.1.2 can easily be backported to Jessie, no changes required (I did it a couple of days ago). Having a 1.1.3 version with a functional toolbar available through backports would great.

**Comment by FKCZ** [comment]
compiled next version from git, on kali-rolling, gnome 3.18, libgtk 3.18, still no toolbar

**Comment by giox069** [comment]
@FKCZ: this issue is a bit old and describes a known problem with remmina 1.1 (master branch). Can you please open a new issue ? In the new issue please describe itf the missing toolbar is the one in windowed mode or the one in fullscreen mode. Also please try to move the mouse at the top or the bottom of the screen and see if something appears.

**Comment by FKCZ** [comment]
@giox069 sorry. System restart solved the issue, which I find somewhat strange, but now I have a working toolbar and everything is ok. After restart, remmina asks me to re-confirm the remote computer certificate, and I had to re-enter password, maybe something left hanging before the restart. Anyhow all is great, thank you Giovanni.

**Comment by giox069** [comment]
@FKCZ: here are 3 informations we newer wrote

1. Remmina up to commit 05cef518583fefc20d83d06eddb9b4dcec2c3101 has a bad way to exit: under Gnome Shell remmina was still running but you were unable to see it. Now things should work better, after commit 05cef518583fefc20d83d06eddb9b4dcec2c3101. This can explain why you needed a system restart.
2. Passwords: with commit 57ec85d8e9bf773b8a08c17a0218b6cd643c828b the password store has been migrated to libsecret, so yes... you must reenter all your password in recent remmina.
3. Certificates: if you have a recent version of freerdp, it's also strongly advised to remove the file `~/.config/freerdp/known_hosts` (not the one ending with '2'), or libfreerdp will be unable to connect to hosts listed in that file.

**Comment by gaetanquentin** [comment]
on ubuntu zesty , gnome shell 3.24, remmina 1.1.2, top bar stay minimized. Unable to use it.

Is there a workaround for it?

**Comment by giox069** [comment]
@gaetanquentin upgrade to remmina 1.2 using our PPA as explained in the [Remmia Wiki](https://github.com/FreeRDP/Remmina/wiki)

**Comment by gaetanquentin** [comment]
@giox069 

ok it works fine now. langage problem fixed too (rdp server remotes were always in english ..)
