### ISSUE TITLE
Full screen toolbar missing in Gnome 3 Ubuntu 15.04

### ISSUE THREAD

**Issue by ryantate13** [FreeRDP/Remmina#564]
Worked fine in 14.10. No RDP connection has the toolbar in full screen mode in 15.04 however. I tried deleting ~/.remmina but that didn't help.

**Comment by giox069** [comment]
Please read FAQ 3 here [Remmina Usage FAQ](https://github.com/FreeRDP/Remmina/wiki/Remmina-Usage-FAQ)

**Comment by ryantate13** [comment]
I see, per the FAQ:
This has been fixed under remmina 1.2.0-rcgit.3 compiled with GTK+ 3.10 or newer.

Is it possible to get version 1.2 through the PPA?

**Comment by giox069** [comment]
At the begining of the [Remmina Wiki Home Page](https://github.com/FreeRDP/Remmina/wiki), you can find the three lines needed to install the "remmina-next" PPA for ubuntu.

**Comment by giox069** [comment]
@ryantate13: can I close this issue ?

**Comment by ryantate13** [comment]
Yes please, I'm sure the PPA issue is not related.


Ryan Tate

**Comment by white-gecko** [comment]
Is there also some keyboard shortcut to close the full screen as a workaround?
The [PPA](https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next) only seams to have 1.1.1 not 1.1.2 as announced on the blog. And the bug still exists in [1.1.2 as in the debian stretch](https://packages.debian.org/stretch/remmina) repos.

**Comment by ssieb** [comment]
You should be able to use right-ctrl and f to get out of full screen, then you can use the toolbar.

**Comment by white-gecko** [comment]
Ah cool, thank you.

**Comment by giox069** [comment]
The PPA shows 1.1.1 in the package name, because we have not yet release an official 1.2 release.
But when you install the remmina-next PPA, you will get a remmina 1.2.0-rcgit.X, the same as the current devel branch (the "next" branch), which includes a newer floating toolbar.
And yes: HostKey+F (by default HostKey is right control), lets you to switch between fullscreen and non fullscreen mode.
