### ISSUE TITLE
Cursor disappear and doesn't refresh in RDP

### ISSUE THREAD

**Issue by opensamba** [FreeRDP/Remmina#598]
Hi,
using remmina in RDP mode to a windows server.
when I'm connecting the mouse cursor works fine, then if I change the focus from Remmina to another application and back to remmina the cursor disappear but exists (I can see the hover of the mouse on some apps).
Similar issue happen if during the same RDP connection the cursor change, 
example: I move the mouse to resize a window or edit an input form.. the mouse change as expected but then the normal arrow cursor doesn't back 

Woraround I found for both issue is: Toggle to scaled mode (but really annoying)

system details:
Arch Linux  LSB Version:	1.4
remmina-git  version : 1.2.0.rcgit.3.r40.g3ccb33e-1
freerdp-git  Version: 1.2.0.beta1.android9.r1654.g5f2fa8a-1

**Comment by jeremyvisser** [comment]
Some more info: https://github.com/FreeRDP/FreeRDP/issues/2755

**Comment by giox069** [comment]
@jeremyvisser: FreeRDP issue 2755 is a regression introduced recently and fixed. opensamba is using an old version of both remmina and freerdp.
@jeremyvisser which version of remmina are you using ? Under which OS ?

**Comment by opensamba** [comment]
@giox069 1.2.0 is an old version? which version should I use to avoid this bug?

**Comment by giox069** [comment]
@opensamba: I just need more specific version from @jeremyvisser to compare with the version you reported at the beginning of this thread. The -rcgit.X part is also useful. Currently we are working on Remmina 1.2.0-rcgit.3 and we hope to switch to 1.2.0-rcgit.4 in a couple of weeks.
I have NEVER seen this bug before, so I'm just trying to reproduce your environment to see this bug.

**Comment by jeremyvisser** [comment]
@giox069 I will try to get back to you with more detail next week some time.

**Comment by jeremyvisser** [comment]
@giox069 The revision of Remmina I was using to test was e2f7db8390c7fde98671c1970254e6fb8e5ebc16. I have tested once again with revision 3ccb33ed77a7729fd44e64120fcdbe0855b09d27 and the behaviour has not improved.

I can reproduce the issue with FreeRDP 358289fb5130fe46cc2f3cbd93c5e2255c890415 but not 16d36e30838b2aa0280cb043d6a8f12aaeaec994.

**Comment by opensamba** [comment]
any luck with this issue?

**Comment by giox069** [comment]
Totally unable to reprocude. I have 2 arch installation of remmina and 4 ubuntus. None of them has cursor problems :(

**Comment by opensamba** [comment]
I can reproduce it! just let me know what you may need and I'll try to send it to you

**Comment by giox069** [comment]
It seems to me that @opensamba and @jeremyvisser are running different versions of remmina and freerdp, so I'm making a lot o confusion.
What I did not understand is:
1. @jeremyvisser: which OS are you running on ?
2. @opensamba and @jeremyvisser: have you tried to recompile freerdp+remmina from the latest sources in ghthub ? I have almost finished a small guide for arch. If you need it, just ask and I will complete it in an hour. In the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) you can find instructions for compilation on Ubuntu and Fedora. But under Ubuntu you can use the provided and updated PPA (see the wiki).
3. @opensamba and @jeremyvisser: have you tried to run xfreerdp and see if the problem is still there ?
4. @opensamba where did you find the packages you mentioned on the 1st post ?
5. Are you running remmina under Xorg or other currently incompatibles Wayland/Mir ?

**Comment by opensamba** [comment]
Hi @giox069 thanks for your reply.

I upgraded, but nothing changes
2.  I'm using version:   remmina-git version : 1.2.0.rcgit.3.r40.g3ccb33e-1
build from the AUR package directly from the git repo: [1] 
3. In freerdp the problem doesn't exist, is remmina-only
4. I builded from the AUR  [1] the tar file is here [2]

5. I'm running remmina under Xorg-server Version : 1.17.2-2

[1] https://aur.archlinux.org/packages/remmina-git/
[2] https://aur.archlinux.org/packages/re/remmina-git/remmina-git.tar.gz

**Comment by giox069** [comment]
@opensamba: are you using freerdp 1.2.0.beta1.android9.r1654.g5f2fa8a-1 from AUR ? Unfortunately it's quite old, and not 100% compatible with remmina 1.2.0.rcgit.3.r40.g3ccb33e-1 from AUR.

**Comment by opensamba** [comment]
@giox069 ok, so which version of freerdp works fine with remmina?

**Comment by giox069** [comment]
@opensamba: there is no perfect version of FreeRDP to use with our latest remmina (our "next" branch here on github). We suggest to use the latest devel FreeRDP (their "master" branch), because we keep our "next" synchronized with their "master".
I have just finished the guide for compiling the latest FreeRDP and Remmina here:
[Compile Remmina on Arch](https://github.com/FreeRDP/Remmina/wiki/Compile-Remmina-on-Arch-Linux). The guide is tested on arch 32 bits. Let us know.

**Comment by giox069** [comment]
@opensamba problem reproduced ! In this arch installation (32bit with openbox window manager), the cursor is not appearing ! Which window manager are you using ?

**Comment by opensamba** [comment]
nice to know is possible to reproduce the problem :)
I'm using gnome 3.16

thanks for the howto, I will try and let you know !

2015-07-16 11:23 GMT+02:00 Giovanni Panozzo <notifications@github.com>:

**Comment by giox069** [comment]
Fix pushed. Please compile and test it.Thank you.
