### ISSUE TITLE
Moving to an embedded version of FreeRDP

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#599]
To distribution maintainers @dktrkranz @Hubbitus (maybe @weberhofer ?). Please @antenore add as many people as you like to the list.

After some internal discussion, discussions with other senior programmers, we decided to embed a specific version of FreeRDP into the code of remmina.
Currently you can find this version in the "remmina_freerdp" branch, and it's working. We hope that we will be able to merge into "next" branch in the next days, after listening to your opinions.

Some note on the embedded version:
 1. FreeRDP libraries will be built statically, to avoid conflicting .so names with your system installed freerdp
 2. You can still disable the embedded version with -DWITH_EMBEDDED_FREERDP=off cmake parameter. This will not build the embedded FreeRDP version and will link as usual with your libfreerdp.so.
 3. The embedded FreeRDP version is an old version with a couple of patches applied. All patches done by the Remmina team has been already pushed upstream to FreeRDP.

**Why we did it ?**
 1. ABI breakages and devel bugs of FreeRDP: there is no afficial freerdp ABI/API around, so FreeRDP programmers are free to do anything they want with their API/ABI. We only had minor problems with this, and immediately fixed. But having more stability in the code will help a lot to lower end-user confusion.
 2. Some distributions repository (Arch AUR) will update only when a FreeRDP release update is released. But the FreeRDP team will not release a 1.2 version in a short period of time: https://github.com/FreeRDP/FreeRDP/issues/2678. So AUR is currently stuck and not working well.
 3. In some other distributions (Fedora ?) there are packages which still need FreeRDP 1.1 (guacamole) and Remmina 1.2 wants FreeRDP 1.2. This is a problem for distribution packagers that cannot include two versions of freerdp in one distribution.

We would like to hear the opinion from distribution package maintainers.

**Comment by dktrkranz** [comment]
Personally, I think this could cause more issues on the long term. Maintaining a private copy of the library could allow for stability of Remmina code now, but more problems will come when integrating code with latest version of FreeRDP.

Speaking for Debian/Ubuntu (but I guess other distributions have similar concerns), we try to avoid embedded libraries as much as we can to avoid security issues, code duplication and linking issues. Our choice would be to prefer linking the "official" library instead of the private one, but if that turns to be too difficult by maintaining patches ourselves without Remmina upstream support is not willing to integrate (because that would break the private FreeRDP copy), it could be difficult to package latest versions in a timely manner, damaging the end user experience.

This issue is a though one, because if FreeRDP is not going to stabilize a bit in the short term (by freezing the code and releasing a stable version), all the software developers requiring FreeRDP will have to reconsider this sooner or later. I would state this in the FreeRDP ticket too.

Another solution distributions could do is to have two distinct libraries packaged, the stable 1.1 and the "development" one, this way software maintainers could choose between the two. This requires some efforts on the packaging side, but can have benefits on the long term, at least until a stable release of FreeRDP occurs.

**Comment by Hubbitus** [comment]
Hello @giox069, @antenore.
It is bad Idea.
Fedora strict prohibid bunle libraries: https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries
As far as I known Debian have siilar policy: http://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

So it sill be a big problem for us.

In many time we do opposite work - ask autors and work tgethe to unbundle libraries from project.

**Comment by antenore** [comment]
Thanks Pavel, we suspected this. Still, we are in a hurry to have a working and stable FreeRDP library, that's why we took this (not final) decision. @dktrkranz asked to our "colleagues" on the other side of the mother Project, https://github.com/FreeRDP/FreeRDP/issues/2678#issuecomment-118784535 

I add you to the discussion, so that you will be aware of new replies.

@dktrkranz Thanks for your support as well.

**Comment by weberhofer** [comment]
Also for (open)SUSE it's problematic to have bundled libraries. There are some exceptions, but its hard to convince reviewers to check in such projects.

**Comment by Hubbitus** [comment]
@antenore thank you for information and effort. I leave comment on linked issue and very hope FreeRDP will freeze some API as it is great project together with remmina.

**Comment by giox069** [comment]
Thank you @weberhofer @Hubbitus @dktrkranz for all the informations provided. I think this project can be aborted and the branch "remmina_freerdp" deleted. @antenore ? (we can also make a local copy of the branch before deleting it, just to have an archive).

**Comment by antenore** [comment]
Yes, I agree.

I've a copy on my server and I guess you have one as well.

I'm going to delete it in around 24 hours and I'll close the issue as well.

**Comment by Hubbitus** [comment]
@giox069, @antenore thank you very much for understanding!

**Comment by Hubbitus** [comment]
Hi.
[https://github.com/FreeRDP/Remmina/releases 1.2.0-rcgit.5] mentioned that issue as fixed. Is it really embedded or not?

**Comment by antenore** [comment]
Not embedded. 

The changelog is generated automatically taking the closed issues and commits.

I fixed the release text.
