### ISSUE TITLE
High DPI display scaling

### ISSUE THREAD

**Issue by Watney** [FreeRDP/Remmina#654]
By chance is there a way to scale Remmina? On my 2560x1700 display, the RDP connection is micro-size. Thanks!!

**Comment by giox069** [comment]
Remmina has an integrated scaler. Just setup your connection profile with a lower resolution (i.e.: 1024x768), and after the connection enable the scaler by clicking on the scaler icon in the connection window toolbar.
It should work in remmina 1.1 and 1.2.

**Comment by Watney** [comment]
Thanks so much. I'll give it a try. (I should have checked the documentation closer before asking. Thanks again!!)

**Comment by rubin110** [comment]
Is there a way to have Remmina specify a scaling factor back to the host machine (Windows)?

I recently got a new laptop with an HDPI display. When I try to connect to my host machine (which runs some photo editing software I can't get for Linux), I get a very large native 1:1 screen making most of the UI in Windows too tiny to use. I can specify a smaller resolution in Remmina and scale on the client side, however this is problematic as it causes unneeded stretching and makes editing photos accurately impossible. If I jump into the display settings (by right clicking on the desktop), the scaling options on these options are disabled due to using RDP.

I see that freerdp offers a scaling-desktop option. Is there anyway to pass this option from the Remmina interface?

Thanks!

**Comment by antenore** [comment]
@rubin110 I opened a new issue for you.
