### ISSUE TITLE
Remmina crashed with core dump while sharing RDP folder

### ISSUE THREAD

**Issue by vadimkim** [FreeRDP/Remmina#659]
I have Remmina 1.2.0-rcgit.4 version on Kubuntu 14.04. Everything works fine unless I want to add shared folder to RDP connection. After selecting the folder from drop-down list I got application crash with the following error:

(remmina:6333): Gtk-CRITICAL **: gtk_tree_model_filter_get_value: assertion 'GTK_TREE_MODEL_FILTER (model)->priv->stamp == iter->stamp' failed

(remmina:6333): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gtype.c:4210: type id '0' is invalid

(remmina:6333): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced
Segmentation fault (core dumped)

May be some library is missing?

**Comment by giox069** [comment]
Hi @vadimkim, thank you for reporting. I remember an old issue #518, which was due to a bug in the integration between KDE and GTK.
See issue #518 if you can find more info.
In the meanwhile, can you post here a backtrace of the crash ? Just open a terminal, start
``gdb remmina``
inside gdb type `run` and then use remmina to reproduce the bug. When remmina will crash, take the terminal and type `bt'. Copy and paste the backtrace here, thank you.

**Comment by vadimkim** [comment]
Thank you, glox069!
I have fixed this by modifying GtkComboBox-appears-as-list: 1 to GtkComboBox-appears-as-list: 0 at gtk.css as described in issue #518. It seems problem with integration still exists. Do you want me to run gdb ?

**Comment by giox069** [comment]
Very well  :)
No, crashdump is not needed. I don't think we have the time to develop a workaround for it.
Just close this issue now.

**Comment by vadimkim** [comment]
Fix is provided
