### ISSUE TITLE
ubuntu 14.04 : remmina passwords blank

### ISSUE THREAD

**Issue by tdemalliard** [FreeRDP/Remmina#679]
Hello,
I have updated to 1.2.0-rcgit.5 yesterday and all my passwords are now blank (empty). They are still present in the password manager (seahorse).
Have a nice day.
##

**Comment by tdemalliard** [comment]
It seems to be related to libsecret migration: https://github.com/FreeRDP/Remmina/pull/653

Is there a way to migrate passwords?

**Comment by antenore** [comment]
I'm very busy now. Hi will take a look ASAP.

**Comment by tdemalliard** [comment]
Take your time, i just wanted to raise the issue wich is not blocking as I can still type the password when connecting.

**Comment by antenore** [comment]
Thanks a lot.
In the meanwhile does libsecret works with new passwords?

**Comment by tdemalliard** [comment]
affirmative:
Password is saved, and does appear with Ubuntu password manager (seahorse).
thanks

**Comment by antenore** [comment]
On Arch I cannot reproduce the issue.
Is your gnome-keyring-daemon running with all components enabled?

``` --components=ssh,secrets,pkcs11
```

**Comment by tdemalliard** [comment]
It may be specific to me only. Do not loose your time until i confirm it.
if I have time this weekend, i will try to reproduce it on a VM running fresh ubuntu 14.04.3.

**Comment by enwony** [comment]
I had same issue (twice, actually).
First time, about 7 month ago, i updated remmina and all passwords in *remmina files was deleted. 
I discovered it too late for any sort of analysis.
Exactly same thing happend few days ago, and I just remebered I updated the system.
All passwords in *remmina files are emptied again.
I've checked dpkg log, since 2015-11-01 [dpkg-log.txt](https://github.com/FreeRDP/Remmina/files/60644/dpkg-log.txt) 
I've found earlier installation. since 2015-10-24
[dpkg-log_prev.txt](https://github.com/FreeRDP/Remmina/files/60646/dpkg-log_prev.txt)

Environment: Ubuntu 15.10 x64, currently remmina 1.2.0-rcgit.6, was (checked earlier log): 1.1.2-ppa1
So, version downgrade may cause this behavior? 
I check that I do not re-enable remmina (freerdp) ppa after upgrade to 15.10.

**Comment by antenore** [comment]
The Gnome team have deprecated libgnome-keyring in favour to libsecret, that's why I've migrated to libsecret.

I didn't suffers any issues during the tests, so I pushed the new backend.

Your passwords are still saved in the gnome-keyring keystore, but unfortunately, there is no way, to migrate one keystore to one another painlessly, or at lease, I didn't find a solution yet.

I was thinking to write a tool for that, but it's a lot of work that I won't commit in the Remmina code anyway, otherwise I'll be obliged to keep the libgome-keyring dependency.

I was also considering to rollback to gnomekeyring, but I don't agree, because otherwise we will stay always with an old code base.
We took the same decision to migrate to GTK3 some months ago and some Remmina supporters were not agree as well.

We want Remmina to be as much in line with the Gnome project as possible, that means we will change often some backends and some libraries, that is inevitable.

If you guys find a smart way to migrate the password from one backend to the other I will love to hear about it, in the meanwhile, except most of the users will come here asking to rolllback, I won't do it.

Hope you understand and that maybe you come up with other solutions.

In the meanwhile try with seahorse to recover the passwords.
