### ISSUE TITLE
SSH agent forwarding, tunnels and other nice stuff

### ISSUE THREAD

**Issue by vadimkim** [FreeRDP/Remmina#692]
Is it possible to define such configuration options as in subj.? It seems SSH functionality is very limited in Remmina - why is it so? 
##

**Comment by antenore** [comment]
Currently, me and @giox069, the only two developers are working on Remmina , we don't need most of that features.

When we have time we try to fix old bugs, improve the existing features and put in place new feature/plugins also based on how many issues are opened concerning one specific needs.

The development around ssh, it's quite complex, also because, libssh, the best library we have found, doesn't support some features out of the box.

Improving ssh will be surely one of my TODO in the future, but at the moment I'm stuck with other issues I want to close.

In the meanwhile, if you are up to it, you can surely grab the source code, read the libssh documentation and try to propose a patch. 

I'll close this because it's duplicated (take a look at the other opened/closed issues and just search for ssh to have a better view) 

https://github.com/FreeRDP/Remmina/search?q=tunnel&type=Issues&utf8=✓

**Comment by vadimkim** [comment]
Thank you for explanation @antenore. I haven't been looking into the code and thought that libssh is like a wrapper around openssl with all the features. Now I see that this is totally different project. Surfing documentation I have found that tunnelling and X11 forwarding is possible with libssh, but not implemented at Remmina. While agent forwarding is a bit more difficult. I have found almost no examples on how to implement it, but such function as  ssh_channel_request_auth_agent makes me believe that this is also possible. 
If you can give me brief introduction to what should I change - I will experiment with SSH agent forwarding. I have found remmina_ssh.c and .h at src/remmina, but didn't find .glade file for UI dialog.
Thank you.

**Comment by antenore** [comment]
The file is the right one and also the function you found looks correct.

I'm not sure as well where should be implemented. The documentation says, implicitly, after a session channel is opened, so, for example, after this line (search for each ssh_channel_new):

https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_ssh.c#L1410

Regarding the UI, you must implement the the ssh option inside the file remmina_preferences.glade

Look what I've done in the pull request #650 to understand better the flow.

**Comment by vadimkim** [comment]
I am confused. According to libssh documentation function *ssh_channel_request_auth_agent*  is present at least since version 0.7 http://api.libssh.org/master/group__libssh__channel.html, but I was not able to find its realization. libssh.h file does not contain this function. I have even installed latest version of libssh - 0.7.2 with the same result.
From the other side function *ssh_channel_open_auth_agent* is present since version 0.6.0. But it should not work without channel request according to the same documentation. This is a dead-end.

**Comment by antenore** [comment]
Thanks a lot for your analysis. Would you mind opening a bug to them (libssh) asking why and how to proceed? In the hope they will answer.

http://red.libssh.org/

**Comment by vadimkim** [comment]
Done.
https://red.libssh.org/issues/215

**Comment by antenore** [comment]
Thanks! Much appreciated. Let's see what they will answer back.

**Comment by antenore** [comment]
Closing as cannot be implemented till libssh 0.8.x will be out, forwarding in general it's in our TODO list$
