### ISSUE TITLE
Failed to load plugin: remmina-plugin-telepathy.so - undefined symbol: remmina_tp_handler_new

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#714]
https://bugzilla.redhat.com/show_bug.cgi?id=1282351

It also reproduced in 1.2.0-rcgit.7
##

**Comment by Hubbitus** [comment]
It also reported in Ubuntu https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/1072457

**Comment by antenore** [comment]
Also in fedora and I expect it's reproducible everywhere we have a new version of telepathy . I'll take a look.

**Comment by antenore** [comment]
I don't think it was working in the past. Anyway, it must be ported to the new dbus implementation, so it will take some time.

**Comment by bulletmark** [comment]
I am on Arch with current official version remmina 1:1.2.0rcgit.24-1. Due to this bug Remmina takes about 15 secs to start everytime which is really annoying. I have tried many other VNC clients but prefer Remmina. It seems a fix for this issue was recently committed, is there a new formal release planned with this fix?

**Comment by antenore** [comment]
@bulletmark Really soon, hopefully before end of this year. It all depends to the last annoying bugs I've to fix in ssh.
