### ISSUE TITLE
Connection search doesn't work

### ISSUE THREAD

**Issue by danboid** [FreeRDP/Remmina#773]
I've noticed that if I push CTRL+f  in the main remmina connection list window a search box appears but it doesn't work. If I type (part of) the name or address of a server that I can see exists within remmina (but isn't currently highlighted) remmina doesn't highlight it when I push enter as I'd expect.

**Comment by danboid** [comment]
remmina 1.2.0rcgit.8-1 under Arch x64

**Comment by antenore** [comment]
The search box is intended to filter (reduce) the list of server while you are typing, is not intended to automatically select a server from the list.

So, if you type something in the search box the list is actually filtered, the search box is working as expected, otherwise there is really a problem.

When you have filtered the list, if you don't want to remove the hands from your keyboard you can maybe use the TAB key till you reach the server list. 

Can you please confirm? If you would like an enhancement can you please edit your first message adding more details?

Thanks

**Comment by danboid** [comment]
Hi Antenore

Unfortunately the search doesn't work in the way you describe either. All of the servers/connections are displayed as I type stuff that should reduce the displayed selection.

**Comment by giox069** [comment]
You are referring to two different search boxes: @antenore is referring to the one on the taskbar, hidden by default. You can enable using a menu option.
@danboid is referring to the standard GTK searchbox which appears when pressing CTRL+F on a list.

@antenore: I think we can try to disable the standard GTK search box on the list, if possible. So users does not get confused.

**Comment by antenore** [comment]
Bizarre, if I have the Quick Search activated, when I hit ctrl+f the cursor is placed automatically inside it.

Sure we can set it to OFF? 

Now I understood, let me take a look. Thanks @giox069

**Comment by giox069** [comment]
I cannot try now, but I can remember that the standard GTK search box appears when you type some alphanumeric char inside the profile list box. I never used CTRL+F to make it appear.

**Comment by antenore** [comment]
Solved, I'm committing and merging

**Comment by antenore** [comment]
@danboid are you able to test the PR #788 ?
Otherwise I can merge it as in any case break the normal Remmina functionalities.

@giox069 Do you agree? I just added an accelerator in the glade file.

**Comment by antenore** [comment]
@danboid tomorrow you should have it in Arch (even now I think), let me know.
