### ISSUE TITLE
How do I select all text in SSH terminal session ?

### ISSUE THREAD

**Issue by box293** [FreeRDP/Remmina#833]
Please give us some details about the systems you are using:
* Linux Mint 17.3 Rosa MATE
* Remmina version 1.2.0-rcgit.11
* Desktop environment : MATE
* Connecting to (OS and version): any linux SSH session
* Connecting via (RDP, VNC, ...): SSH

Issue / Question:
How do I select all the text in the terminal screen so I can copy it to clipboard? I cannot find a way to assign a hotkey to it. I can only do it with a mouse and lots of scrolling while holding the mouse button down.

**Comment by antenore** [comment]
Thanks for the report.
This is not yet implemented and I'm not sure is it possible (tested with vte command), I'll take a look at it.

If you use screen or tmux it's quite straightforward

http://askubuntu.com/a/55163/8111

**Comment by antenore** [comment]
xfce4-terminal is based on vte, as remmina, so I should be able to do something

**Comment by box293** [comment]
Thanks for the link to the tips using screen or tmux. However they all seem a bit convoluted. 

All I need is a menu option (perhaps from a right click) that simply selects all text, being a keyboard shortcut is not important. From there I can copy and paste using normal commands. 

It's not something I'm in a rush for, but I thought I would throw the idea out there

Thanks for the quick response :)

**Comment by antenore** [comment]
I was too excited to add it.

A quite hidden feature was the Host+c and Host+v keys (Host --> right ctrl), that you can use for copy and paste.

So I added a Host+a (right ctrl+a), to select everything and I also created a popup menu with the 3 commands, so that you can use both the mouse or the keyboard.

Before to merge this branch (vte_improvements) into next, I want to test it on different distros (so far FreeBSD and Ubuntu 15.10), if you are up to it, you can compile your self and test it, otherwise you can wait the merge + 1 day to have it in the PPA.

@giox069 for info

**Comment by box293** [comment]
Awesome, that’s exactly what I was after. I'm a big fan of the copy and paste keys, so having another keyboard shortcut is great. I'll wait for it to come through in PPA.

It's awesome to have open source products like this be actively developed, keep up the great work.

**Comment by gnumdk** [comment]
This break Ctrl + C in ssh sessions...
