### ISSUE TITLE
Only access via Administrator account (Raspbian -> Windows 10)

### ISSUE THREAD

**Issue by jobv8x** [FreeRDP/Remmina#880]
Hi,

I'm trying to connect a Windows 10 PC via Remmina (installed on Raspberry PI 3). I can only set-up a connection via the Administrator account of the Windows 10 pc. For each other user we get an error. 

Unable to connect to RDP server 192.xxx.xxx.xxx

What are we doing wrong?

**Comment by antenore** [comment]
Hi @jobv8x ,

this is because your windows policy allow remote connections only from the administrator account.

I'm not an expert in windows administration any more so I cannot guide you that much, sorry.

So, this is not a Remmina development issue (I close this).

You can post in our G+ community and ask for support there, we have some really strong windows experts over there. 

https://plus.google.com/communities/106276095923371962010
