### ISSUE TITLE
RDP Plugin - "Nothing provides libfreerdp-client.so.2()(64bit)

### ISSUE THREAD

**Issue by Dolphykins** [FreeRDP/Remmina#914]
Client: Fedora 24, Kernel 4.5.7-300.fc24.x86_64
Remmina Version 1.2.0, Release 0.19.rcgit.14.fc25
Gnome Shell 3.20.2

Follow-up with a different issue from this thread:
https://github.com/FreeRDP/Remmina/issues/899

After manually installing the latest release of Remmina from RPM (remmina-1.2.0-0.19.rcgit.14.fc25), and trying to install the x86_64 RPM for the RDP plugin (remmina-plugins-rdp-1.2.0-0.19.rcgit.14.fc25.x86_64.rpm), dnf and the software installer are both reporting that I'm missing a library for FreeRDP.

FreeRDP is installed and the latest version (2.0.0-5.git.b02943a.fc24) along with freerdp-libs. I tried uninstalling and reinstalling to make sure. "libfreerdp-client.so.2.0" is in /usr/lib64, and I tried making a symlink as "libfreerdp-client.so.2", one in /usr/lib and one in /usr/lib64, which did not fix the missing dependency issue.

**EDIT:** Updated description to reflect installed Remmina version.
##

**Comment by antenore** [comment]
This is more a packaging issue and not a FreeRDP/Remmina problem.

@hubbitus can you please help?

**Comment by giox069** [comment]
[giovanni@mybsd ~/remmina_devel/Remmina]$ make
Scanning dependencies of target remmina
[  1%] Building C object remmina/CMakeFiles/remmina.dir/src/remmina_file.c.o
/home/giovanni/remmina_devel/Remmina/remmina/src/remmina_file.c:644:7: 
warning: implicit declaration of function
       'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
                 if (utimensat(AT_FDCWD, remminafile->filename, times, 
0) < 0)
                     ^
1 warning generated.
[  2%] Linking C executable remmina
CMakeFiles/remmina.dir/src/remmina_file.c.o: In function 
`remmina_file_touch':
/home/giovanni/remmina_devel/Remmina/remmina/src/remmina_file.c:644: 
undefined reference to `utimensat'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/giovanni/remmina_devel/Remmina
*** Error code 1

Stop.
make[1]: stopped in /usr/home/giovanni/remmina_devel/Remmina
*** Error code 1

Stop.
make: stopped in /usr/home/giovanni/remmina_devel/Remmina

**Comment by giox069** [comment]
Ah, ecco... non esiste utimensat() nella 10.2.


Come si fa l'upgrade alla 10.3 ?

**Comment by antenore** [comment]
On 06/23/2016 23:26, Giovanni Panozzo
      wrote:
    
    
      Ah, ecco... non esiste utimensat() nella 10.2.
      
      
      Come si fa l'upgrade alla 10.3 ?
      
    
    sudo freebsd-update fetch
    sudo freebsd-update install -r 10.3-RELEASE
    
    Con riserva perché vado di memoria... Cerco, intanto fai il fetch
    
    
    
      
      On 23.06.2016 23:22, Antenore Gatta wrote:
      >
      > This is more a packaging issue and not a FreeRDP/Remmina
      problem.
      >
      > @hubbitus <https://github.com/hubbitus> can you please
      help?
      >
      > —
      > You are receiving this because you are subscribed to this
      thread.
      > Reply to this email directly, view it on GitHub 
      >
<https://github.com/FreeRDP/Remmina/issues/914#issuecomment-228187921>,
      
      > or mute the thread 
      >
<https://github.com/notifications/unsubscribe/AFOVqz3AUTQo5ML7vGR_IzJapa4yK92bks5qOvkJgaJpZM4I9PX2>.
      >
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by giox069** [comment]
> sudo freebsd-update fetch
Ok, questo fatto e sembra corretto.

> sudo freebsd-update install -r 10.3-RELEASE
Questo invece no.

**Comment by antenore** [comment]
On 06/23/2016 23:26, Giovanni Panozzo
      wrote:
    
    
      Ah, ecco... non esiste utimensat() nella 10.2.
      
      
      Come si fa l'upgrade alla 10.3 ?
    
    
    freebsd-update fetch
    freebsd-update -r 10.3-RELEASE upgrade
    freebsd-update install
shutdown -r now
# Se hai tempo i seguenti
pkg-static upgrade -f
portmaster -af
# e ancora

freebsd-update install


    
      
      
      On 23.06.2016 23:22, Antenore Gatta wrote:
      >
      > This is more a packaging issue and not a FreeRDP/Remmina
      problem.
      >
      > @hubbitus <https://github.com/hubbitus> can you please
      help?
      >
      > —
      > You are receiving this because you are subscribed to this
      thread.
      > Reply to this email directly, view it on GitHub 
      >
<https://github.com/FreeRDP/Remmina/issues/914#issuecomment-228187921>,
      
      > or mute the thread 
      >
<https://github.com/notifications/unsubscribe/AFOVqz3AUTQo5ML7vGR_IzJapa4yK92bks5qOvkJgaJpZM4I9PX2>.
      >
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by antenore** [comment]
Sorry, I've answered to the wrong threads.
I deleted the bad ones .

**Comment by Dolphykins** [comment]
I removed Remmina and all of its plugins, downloaded 1.2.0-0.18.rcgit.14.fc25.x86_64 and its respective RDP plugin, and I'm getting the same error for the same library.

**Comment by Dolphykins** [comment]
Bump, checking to see if this has been fixed yet. I've reverted my laptop to Remmina from repos (0.13.rcgit.7.fc24 as of writing) in order to get atleast RDP working, just using Gnome-Terminal for SSH until a new build is pushed to resolve the issue from the previous case.

**Comment by antenore** [comment]
We don't have control over the fedora packages.

I advice you to follow our wiki to build freerdp and remmina from the sources, it's quite easy and fast.

In the meanwhile we'll wait an answer from the Fedora team.

Later I'll add some more details.

**Comment by waynewinchjr** [comment]
I agree it's a packaging issue.  These steps can give you an F25 remmina with RDP, VNC and SSH working; however, be advised that performing these steps can lead to instability in remmina, potentially even induce crashes, though I have yet to see one with light use.  **Thus, you should not execute these steps on any Production systems.  YOU HAVE BEEN WARNED!!!**

BTW, @antenore has the proper suggestion: get freerdp and remmina sources, build artifacts and install them.  Has anyone opened a Fedora Bugzilla report concerning this issue in the hopes of getting a proper F24 solution?

1. Uninstall remmina and all plugins from F24.
2. Obtain remmina-1.2.0-0.19.rcgit.14.fc25.x86_64.rpm, remmina-plugins-rdp-1.2.0-0.19.rcgit.14.fc25.x86_64.rpm and remmina-plugins-vnc-1.2.0-0.19.rcgit.14.fc25.x86_64.rpm from the Fedora Package Database at https://admin.fedoraproject.org/pkgdb/.
3. Install remmina and remmina-plugins-vnc (if required) RPMs.  They should install cleanly in to F24.
4. Install remmina-plugins-rdp with the rpm --nodeps option to get around dependency breakage.
5. Symbolically link /usr/lib64/libfreerdp.so.2 to /usr/lib64/libfreerdp.so.2.0.
6. Symbolically link /usr/lib64/libfreerdp-client.so.2 to /usr/lib64/libfreerdp-client.so.2.0
7. Symbolically link /usr/lib64/libwinpr.so.2 to /usr/lib64/libwinpr.so.1.1.  This, IMHO, is the riskiest step as it swaps a later shared library for one of an earlier version; I was unable to locate the equivalent F25 libwinpr package to use.

Hope this helps someone.

**Comment by antenore** [comment]
Thanks a lot @waynewinchjr , this is much appreciated.

These steps are more than correct and it's less slickly to give troubles than the standard package provided by default.

> Has anyone opened a Fedora Bugzilla report concerning this issue in the hopes of getting a proper F24 solution?

I'm 100% agree, but I'm not a regular Fedora 24/25 user, so I'd not be able to answer questions to the FreeRDP supporters.

The second issue is that they won't probably support you because the least FreeRDP (and so Remmina) hasn't been officially released yet (we are waiting our big bros). Till that moment distributions like Fedora and Debian they will provide and support only old FreeRDP and Remmina versions. :-\ 

I'd try to contact @hubbitus (Pavel Alexeev) and the others that have packaged Remmina.

 http://koji.fedoraproject.org/koji/packageinfo?packageID=10031

BTW, did you both have tested the koji packages?

**Comment by waynewinchjr** [comment]
Why @antenore, you are quite welcome!  I did not install the koji packages directly, just those I found on the Fedora Package DB.

I'd like to personally thank you and other developers, testers, documentarians, etc., for the tireless and sometimes thankless work you do to bring FreeRDP and Remmina to the world.  These tools truly are best-of-breed and open to boot.  Bravo!

I've included a shout out to @Dolphykins in case the posted info is useful.

**Comment by antenore** [comment]
Thanks :-)

**Comment by Hubbitus** [comment]
I'm very sorry for the late reply. Does this issue still happened for you in Fedora 24?

**Comment by waynewinchjr** [comment]
Sorry, @Hubbitus, for the AFK.  Yes, this particular issue happens in F24.  The core issue of Remmina appearing to hang on SSH (which seems to perhaps be a VTE issue as Wireshark shows the SSH connection completing successful, AFAICT), I believe, is fixed in the FC25 (Rawhide) version of Remmina and the Remmina RDP plugin.

When performing my kludgy workaround above with the Rawhide Remmina, the libwinpr version bump compared to F24 has me concerned as I've seen a couple of impromptu crashes (sudden RDP/SSH window closes I hadn't seen in a normal Remmina install).

I might install a Rawhide VM and see if Remmina works there without issue.  We might just be dealing with incompatibilities brought about by trying to install Rawhide packages on a release system, so I don't want to have you chasing ghosts.

I'm guessing that backporting Remmina 1.2.0-0.19.rcgit.14.fc25 to F24 (making this version available as an update to the existing 1.2.0-0.13.rcgit.7.fc24 package) is totally out of the question, or is it?  Hey, a guy can dream... ;-)

**Comment by Hubbitus** [comment]
As we always wait freerdp ABI stability I think we can't just build so new version for Fedora 24. Just because there no freeze and backward capability just not maintained. For the long time in the past I've maintain COPR repository https://copr.fedorainfracloud.org/coprs/hubbitus/remmina-next/ . Does it helpful for you?

**Comment by antenore** [comment]
@Hubbitus yes, it is, I've used it sometimes. We must update our wiki.

**Comment by ic3d** [comment]
Since this issue is a packaging one only on Fedora 24, and F24 it reached end of life in 2017-08-08, we can close this issue.
