### ISSUE TITLE
Remmina is not aware of additional screen added

### ISSUE THREAD

**Issue by ringe** [FreeRDP/Remmina#938]
I move the Remmina main window to the newly connected display on my laptop:
- I open an RDP connection and enable fullscreen.
- The fullscreen connection jumps back to the laptop's main display.

If I close Remmina and open it after the the new display is connected and then move the main window to the new dusplay:
- I open an RDP connection and enable fullscreen.
- The connection goes fullscreen on the correct display.

Remmina should update the setting of which screen to go fullscreen on after a new display is plugged in.
- Client (OS name and version): Ubuntu 16.04
- Remmina version (remmina --version): Version 1.2.0-rcgit.13 (git n/a)
- Desktop environment (GNOME, Unity, KDE, ..):  GNOME
- Connecting to (OS and version): Any
- Connecting via (RDP, VNC, ...): RDP
- RDP issues only, freerdp version (xfreerdp --version): none

PS: I love Remmina. It's an essential everyday tool.
##

**Comment by ComputingFroggy** [comment]
This is weird: I am also running Ubuntu Gnome 16.04 (although I've upgraded to the latest Gnome 3.20 version) and I don't have the same behaviour.

No matter what I do the full screen goes to the laptop screen, even if the external screen is already connected, set as primary screen and Remmina is started from that screen. I do get a Remmina session with the external screen resolution (I've chosen "Use Client resolution") but as soon as I clic on full screen Remmina switches to the laptop screen instead of staying on the external monitor.

I am using a Thinkpad T420. Any indications, on how to solve this, would be helpful.

**Comment by ringe** [comment]
Did you shut down Remmina? I ask because it took me a while to discover that remmina sits in the system tray after closing it with the cross in the corner.

Try killing all remmina processes and open it again while the external display is plugged in.


Den 3. august 2016 16.27.16 CEST, skrev ComputingFroggy <notifications@github.com>:
>This is weird: I am also running Ubuntu Gnome 16.04 (although I've
>upgraded to the latest Gnome 3.20 version) and I don't have the same
>behaviour.
>
>No matter what I do the full screen goes to the laptop screen, even if
>the external screen is already connected, set as primary screen and
>Remmina is started from that screen. I do get a Remmina session with
>the external screen resolution (I've chosen "Use Client resolution")
>but as soon as I clic on full screen Remmina switches to the laptop
>screen instead of staying on the external monitor.
>
>I am using a Thinkpad T420. Any indications, on how to solve this,
>would be helpful.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeRDP/Remmina/issues/938#issuecomment-237244070

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ComputingFroggy** [comment]
Yes, I did shut down Remmina,as I can see it in the system tray.
And the external monitor is always connected !

**Comment by ComputingFroggy** [comment]
Just for information, I have no problems when using 2 screens on my desktop PC (still running Ubuntu Gnome 16.04 and latest Remmina).
So this is a problem related to the Thinkpad T420 ... still any indications on how to solve this would be helpful as I am using the laptop on a regular basis.

**Comment by ComputingFroggy** [comment]
I have found the culprit: it is a Gnome extension, Clipboard indicator.
I have logged a bug : https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/44.

a strange bug: when using Remmina (RDP client) to connect to a terminal server from a secondary monitor, the full screen session is opened on the primary monitor (instead of the secondary).
If I disable Clipboard indicator extension, all is OK.

**Comment by antenore** [comment]
I'm impressed! Well done!

**Comment by ringe** [comment]
I don't have that extension. And this only happens if Remmina is open when I add a display.


Den 7. august 2016 14.12.03 CEST, skrev ComputingFroggy <notifications@github.com>:
>I have found the culprit: it is a Gnome extension, Clipboard indicator.
>I have logged a bug :
>https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/44.
>
>a strange bug: when using Remmina (RDP client) to connect to a terminal
>server from a secondary monitor, the full screen session is opened on
>the primary monitor (instead of the secondary).
>If I disable Clipboard indicator extension, all is OK.
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeRDP/Remmina/issues/938#issuecomment-238078993

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ic3d** [comment]
Hi @ringe we're reviewing old open issues, do you still get this one? Thanks!

**Comment by ringe** [comment]
Hi @ic3d I don't get this one on Ubuntu 17.04 and Remmina 1.1.2

**Comment by erichoog** [comment]
I have a similar issue to what the OP has posted here.  

When I use the full screen option the connection will go fullscreen on whatever Monitor that the main Remmina window is located on, rather than going fullscreen on the window which the current Remmina connection window is located.  

I am not adding a new screen but what I do is open Remmina and log into two different Windows machines all on my second monitor.  I then split out the second connection and make it fullscreen so that it stays on the second monitor.  I then drag the main Remmina window and the first connection window to my first monitor and do full screen.  If I do not move the main Remmina window then the first connection window will go fullscreen on my second monitor.  

I'm not sure if this is relevant to this issue but it sounded similar to what I was experiencing.

I'm on Arch Linux, KDE Plasma 5.10.5-1, and Remmina 1.2.0-rcgit-20 (git rcgit-20)

**Comment by ic3d** [comment]
Hi @erichoog please open a new issue, since this one is closed. Thanks!
