### ISSUE TITLE
Add RDP scaling factor as implemented by FreeRDP 

### ISSUE THREAD

**Issue by antenore** [FreeRDP/Remmina#969]
Copied from #654 comment posted by @rubin110

> Is there a way to have Remmina specify a scaling factor back to the host machine (Windows)?
> 
> I recently got a new laptop with an HDPI display. When I try to connect to my host machine (which runs some photo editing software I can't get for Linux), I get a very large native 1:1 screen making most of the UI in Windows too tiny to use. I can specify a smaller resolution in Remmina and scale on the client side, however this is problematic as it causes unneeded stretching and makes editing photos accurately impossible. If I jump into the display settings (by right clicking on the desktop), the scaling options on these options are disabled due to using RDP.
> 
> I see that freerdp offers a scaling-desktop option. Is there anyway to pass this option from the Remmina interface?
> 
> Thanks!

**Comment by giox069** [comment]
Hi @rubin110, yes, I think we can do it. Do you mean the option "/scale:X" of xfreerdp ? It seems to request the server to draw all objects scaled, but server pixels still have 1:1 mapping to your screen pixels. Do you know why FreeRDP only accepts 100, 140, 180 as scaling factors and no other factors ?

**Comment by antenore** [comment]
It seems the scaling factor is (let's say) imposed by Windows, as are the only scaling factor they were using (checked some docs on internet)

For example:

http://www.anandtech.com/show/7939/scaling-windows-the-dpi-arms-race/5

Probably with these factors the image keep its properties without being deformed?

Some useful information on how is documented/managed today my M$

https://msdn.microsoft.com/windows/uwp/layout/screen-sizes-and-breakpoints-for-responsive-design 

... But I don't see anything that is logic :-\

**Comment by antenore** [comment]
OK, found some cool information:

https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.display.resolutionscale.aspx

So the default are the one used by FreeRDP, I think we can implement all of them (must be changed in freerdp aswell?)

https://code.msdn.microsoft.com/windowsapps/Scaling-sample-cf072f4f

**Comment by rubin110** [comment]
This is the current command I use with a recent nightly of freerdp to achieve approximately something useful...

`/opt/freerdp-nightly/bin/xfreerdp /u:xxx /p:xxx /v:1.2.3.4 /w:2560 /h:1440 /scale-desktop:150 /scale-device:140 +fonts /compression:off /bpp:32`

I believe scale-device is specific for a different class of apps in Windows 10 and don't quite understand it, additionally it only accepts values of 100, 140 and 180.

**Comment by giox069** [comment]
Official RDP doc here: https://msdn.microsoft.com/en-us/library/cc240510.aspx
There are 2 parameters involved: **desktopScaleFactor** (_/scale-desktop:_ on xfreerdp) and **deviceScaleFactor** (_/scale-device:_ on xfreerdp). When you use _/scale:_ on xfreerdp, you set both with the same value (see FreeRDP's ./client/common/cmdline.c).
I'm working on an implementation with global RDP settings. Scaling factor should be choosen one for every local monitor, and should be automatically guessed from the current running system. But for our 1st implementation, a global setting will be enough :)

**Comment by giox069** [comment]
@antenore: branch issue969 is ready for testing, if you can :)

**Comment by antenore** [comment]
Cool! In 5 hours I'll have the opportunity to test this.

Thanks!

**Comment by antenore** [comment]
I'm testing it.
Do you think it's too hard to have these settings on a per profile basis instead of being global?

So far I've got just an issue with something that should not be related, but I cannot check if it's a regression till tomorrow. Going full screen mode, and switching between "keep aspect ratio when scaled" and "Fill client window when scaled" was giving me a black screen in "keep aspect ratio...". This disappeared after a couple of minutes working with Remmina.

Consider that my setup is quite particular at the moment:

FreeBSD --> Remmina -> Spice plugin --> Fedora 23 KVM --> Remmina --> RDP plugin --> My 2008 R2 server.

To resume:

1) I don't have the perfect setup to test it
2) Except a temporary problem I got, probably due to QXL bugs, everything seems to work properly.
 
That's all at the moment, tomorrow morning I'll test much more.

@rubin110 do you mind compiling this branch and test as well?

**Comment by giox069** [comment]
1. Per profile scaling settings: can be done per profile. But I think it's quite confusing, because scaling is something related to your local monitor(s), not the remote profile. And if we implement it now, we will never be able to remove it in the future (users of the feature will complain a lot). So... let's wait user comments and decide later.
2. I investigated on an automatic mode: gtk has [gdk_screen_get_monitor_scale_factor ()](https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-get-monitor-scale-factor) which automatically detects your monitor scaling factor. But as explained in [Issue#6](https://github.com/FreeRDP/Remmina/issues/6#issuecomment-241471607) remmina knows in which monitor your RDP windows will be only after the RDP connection, so it's hard to detect the correct current monitor and its scaling before the remote connection.
3. Let me know about your issue :)
4. I did some testing: it seems that Windows 2012 R2 is correctly using both parameters, desktopScaleFactor for desktop apps and deviceScaleFactor for "metro" apps. Windows 10 seems to be using only desktopScaleFactor for both normal and appstore apps. ignoring deviceScaleFactor.
