### ISSUE TITLE
Remmina not showing entire desktop, Windows Remote Desktop Connection does.

### ISSUE THREAD

**Issue by penalvch** [FreeRDP/Remmina#986]
>"We support Remmina 1.2+ versions only. Please do not report bugs occurring on older versions!"

While this is understood, Ubuntu is still using 1.1.2 in their latest supported repository (i.e. not PPA). Hence, courtesy support is requested, and greatly appreciated.

The issue seems a regression from https://github.com/FreeRDP/Remmina/issues/534 .
Please give us some details about the systems you are using:
* Client (OS name and version): lsb_release -rd
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

* Remmina version (remmina --version): remmina --version
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
option parsing failed: Unknown option --version

apt policy remmina
remmina:
  Installed: 1.1.2-3ubuntu1
  Candidate: 1.1.2-3ubuntu1
  Version table:
 *** 1.1.2-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

* Desktop environment (GNOME, Unity, KDE, ..): gnome-flashback-compiz

* Connecting to (OS and version): lsb_release -rd
Description:	Ubuntu 16.04.1 LTS
Release:	16.04

apt policy remmina
remmina:
  Installed: 1.1.2-3ubuntu1
  Candidate: 1.1.2-3ubuntu1
  Version table:
 *** 1.1.2-3ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

* Connecting via (RDP, VNC, ...): XRDP to VNC

* RDP issues only, freerdp version (xfreerdp --version): N/A

Thank you for your time and consideration in this matter.

![screenshot](https://cloud.githubusercontent.com/assets/8216601/18153214/94c33888-6fc1-11e6-87d0-06faf413ef1f.png)

**Comment by antenore** [comment]
This is an old version we really cannot support anymore.

Please install the PPA as described in our wiki home page.

Thanks

**Comment by penalvch** [comment]
antenore, thanks for the quick response.

As per https://github.com/FreeRDP/Remmina/wiki the 1.1.2 stable branch is eligible for bug fixes. Hence, could you please either:
1) Reopen this bug.
2) Both fix the wiki to note 1.1.2 is not eligible for bug fixes, and have the 1.2 branch backported to Xenial+ in Ubuntu via https://wiki.ubuntu.com/StableReleaseUpdates.

I'm fine with either way really, as long as one of the above is done, as PPAs aren't considered supported by the Ubuntu project.

**Comment by antenore** [comment]
That is a mistake indeed because there is a package naming issue (that we are fixing), I'll clarify the wiki asap.

This is the last available version (1.2.0-rcgit-15)

```
$ remmina --version
remmina - Version 1.2.0-rcgit-15 (git cfbfe36)
```

I really push you to update it because we have fixed tons of issues and added several new features.
I cannot bet you will be happy with it, but I hope so and in the case you will need support, we will have everything we need to do it.

**Comment by antenore** [comment]
@nastasi can you please answer the Debian/Ubuntu way about this issue?
Thanks!!!

**Comment by giox069** [comment]
No, I don't think we have versioning problems now.
The full story is
- Remmina 1.1.X is our current master branch, and is considered stable. It's used by both Debian and Ubuntu as main stable source for remmina.
- Remmina 1.2.X is our current "next" branch. Its quite-stable, we could mark it as "stable", but it will not help you to have remmina 1.2.X into Ubuntu/Debian, because... (continue reading)

Remmina 1.2.X depends on FreeRDP 2.0, which is currenty in a "never-released", unstable state. Debian/Ubuntu can only include stable software on their distro. This means that they cannot include FreeRDP 2.0, and this means **they cannot include Remmina 1.2.X in their distributions**.

We could allocate some time to fix a problem in Remmina 1.1.X, but:
a) We have to move our limited development time from 1.2 to 1.1
b) A "big" code fix in 1.1.X will be shipped to you only in the next ubuntu release. Usually distro maintainers accept fixes in the current release only for critical (crashes, data corruption) or security bugs. In this case, a feature that never worked, when fixed, is sometime considered as a new feature. And new features will go on the next distribution release, not the current one.
c) The majority of Remmina users are using the PPA with remmina 1.2 (or the equivalents COPR in fedora, AUR in arch), so we can push fixes immedialtely. Users of the standard remmina 1.1.X should be a minority now.

So: I don't think fixing 1.1.X is a wise way to invest our very limited development time. Nor it's the best way to have the fix pushed to our users.
We found that the most efficient way to invest our time to help ubuntu users is through the PPA. And we do our best effort to in keeping the PPA in good health and not breaking it.

Yes, you can still fix it by yourself in the usual github way: fork, create a pull request and we will test and merge, then you should ask the ubuntu maintainers to accept the fix as soon as possible. If you can do that, your help will be much appreciated.

**Comment by antenore** [comment]
So we won't fix this except someone else will have:

1) The time to do it
2) The competencies and "power" to make it happens.

**Comment by giox069** [comment]
@antenore: I will write something on the wiki later :)

**Comment by penalvch** [comment]
@antenore / @giox069, thanks for the continued discussion towards this. It is greatly appreciated.

With this in mind, I do want to clear up a few misconceptions regarding Ubuntu:
> No, I don't think we have versioning problems now. The full story is Remmina 1.1.X is our current master branch, and is considered stable. It's used by both Debian and Ubuntu as main stable source for remmina. Remmina 1.2.X is our current "next" branch. Its quite-stable, we could mark it as "stable", but it will not help you to have remmina 1.2.X into Ubuntu/Debian, because... (continue reading) Remmina 1.2.X depends on FreeRDP 2.0, which is currenty in a "never-released", unstable state. Debian/Ubuntu can only include stable software on their distro.

IMHO, given the PPA is considered stable upstream due to how:
1) It is a source for new upstream patches to be included quickly for testing and for use for Ubuntu users.
2) Where all development resources are going.
3) What vast majority of users use as per your data.

The 1.1.X branch would be considered "legacy" and 1.2.X PPA "stable" with github 1.2.X being "unstable". Hence, 1.2.X PPA is eligible for inclusion into Ubuntu Xenial+ as outlined in https://wiki.ubuntu.com/StableReleaseUpdates.

> This means that they cannot include FreeRDP 2.0, and this means they cannot include Remmina 1.2.X in their distributions.

I'm not sure the previously provided rationale indicates this. As per https://launchpad.net/ubuntu/+source/freerdp FreeRDP 2.0 may be included in Xenial+ as per previous SRU URL.

> We could allocate some time to fix a problem in Remmina 1.1.X, but: a) We have to move our limited development time from 1.2 to 1.1 b) A "big" code fix in 1.1.X will be shipped to you only in the next ubuntu release.

As per https://launchpad.net/ubuntu/+source/remmina the next release has come and gone already with no update to the 1.1.X branch. :(

> Usually distro maintainers accept fixes in the current release only for critical (crashes, data corruption) or security bugs.

Ubuntu accepts fixes as per SRU process in all supported releases (even the very oldest), irrespective of criticality.

> In this case, a feature that never worked,

The feature did work, and was working fine for me, as it is a regression from #534.

> when fixed, is sometime considered as a new feature. And new features will go on the next distribution release, not the current one.

The problem reported here is not a new feature. It's a bug fix to a current feature. Even if one were to interpret a fix as a new feature, it can be accepted into Ubuntu via SRU process. ;)

> c) The majority of Remmina users are using the PPA with remmina 1.2 (or the equivalents COPR in fedora, AUR in arch), so we can push fixes immedialtely. Users of the standard remmina 1.1.X should be a minority now.

To clarify, are you basing this off data or hunch? IIRC there would be a way to have hard data from Ubuntu, as Ubuntu has a feature that anonymously reports packages installed (if the user allows it), so one may get a true picture of install base of both PPA and version from supported Ubuntu repositories.

> So: I don't think fixing 1.1.X is a wise way to invest our very limited development time. Nor it's the best way to have the fix pushed to our users. We found that the most efficient way to invest our time to help ubuntu users is through the PPA. And we do our best effort to in keeping the PPA in good health and not breaking it. Yes, you can still fix it by yourself in the usual github way: fork, create a pull request and we will test and merge, then you should ask the ubuntu maintainers to accept the fix as soon as possible. If you can do that, your help will be much appreciated.

Sounds like the PPA and the latest 1-2 releases of Ubuntu should mimic one another in terms of version, so that stable users don't become disconnected from upstream development work, and official Ubuntu project support simultaneously. There are a number of projects who do it this way to much fanfare of Ubuntu users, and developers. For example, LibreOffice as per:
- https://launchpad.net/~libreoffice
    - These are the PPA maintainers, with various PPAs available for unstable/stable testing, and where Ubuntu sources fixes from into all supported releases.
- https://launchpad.net/ubuntu/+source/libreoffice
    - Supported packages, that include latest version of LO in latest two releases.

Despite this, I'm downloading an ISO now to test the PPA so I may confirm the 1.2.X PPA branch does indeed fix my issue.

**Comment by antenore** [comment]
Thanks for the great explanation... 
I'll never grasp completely these arcane Ubuntu/Debian concepts honestly, I'm waiting the comments from Matteo (@nastasi) .

Regarding remmina usage statistics we are quite sure of what we are speaking about.

The rest if you prefer we can discuss also on IRC, as I'm not English mother tongue, it may be wrongly understood/interpreted (my bad).

Now the main issue is that we don't have the time to support that version, we just don't have time, full stop.

We do this in our free time because we are first of all Remmina users, so each one of us, fix and extend what he needs, what he likes to fix and what he think it really make sense to be fixed.

If you think that this must be fixed and you are up to it (I'm quite sure you are), you are more than welcome to help us, in that sense we will never say not. 

Matteo is fixing the PPA issues and we are finally releasing FreeRDP with Remmina... So I think, even if I don't really understand nothing about how Ubuntu works (sorry I'm a *nix nerd), that we are going in the right direction.

Please test the new version, you will LOVE it ;-) we have also Spice now, a screenshot tool, a new flaming UI and we fixed tons of bugs (and much much more).

As I was saying, it looks like you know really well of what you are speaking about, so join us and help Matteo, I'm sure he will love to have some help and if we can support again the master branch, why not, but don't ask to me and Giovanni to do it, because we cannot, we have other priorities.

I reopen this till we aill find the solution or the compromise.

**Comment by penalvch** [comment]
@antenore, thanks for the quick follow up. Your English is excellent, and the support rationale makes complete sense (happy to IRC if you would prefer).

The SRU process may seem different, but it is how fixes get backported in Ubuntu.

Despite this, the issue is confirmed fixed in the PPA:
1.2.0~rcgit-15+979+next+201608300914~ubuntu16.04.1

Given this, I'll start documenting the SRU action items in https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/1619094 and hopefully this will be less arcane than it initially seemed.

**Comment by antenore** [comment]
This change everything, I'll take a look asap.

**Comment by penalvch** [comment]
Problem solved after recent supported repository updates.

**Comment by antenore** [comment]
Thanks
