### ISSUE TITLE
[Feature Request] Import from RDP file or files

### ISSUE THREAD

**Issue by Justinzobel** [FreeRDP/Remmina#997]
The ability to import or export to/from RDP files would be great and a good way to sync between windows and linux workstations for saved RDP connections.

**Comment by antenore** [comment]
Drag&drop rdp files into remmina already work.
What we don't know yet how to do, is to associate the RDP files to remmina, so that you can double click on them. 

In the feature (hopefully), we will modify slightly the interface to make it more clear.

If you don't mind I'll close this as duplicated, but I cannot find the original issue.

**Comment by Justinzobel** [comment]
Thanks. Works for me.

**Comment by antenore** [comment]
thx.
